fn docs_build_or_serve_subprocess(
    args: &[String],
    common: &DocsCommonArgs,
    label: &str,
) -> Result<(serde_json::Value, i32), String> {
    if !common.allow_subprocess {
        return Err(format!("{label} requires --allow-subprocess"));
    }
    if label == "docs build" && !common.allow_write {
        return Err("docs build requires --allow-write".to_string());
    }
    let ctx = docs_context(common)?;
    let site_paths = bijux_dev_atlas::docs::site_output::parse_mkdocs_site_paths(&ctx.repo_root)?;
    let output_dir = ctx.repo_root.join(&site_paths.site_dir);
    if label == "docs build" {
        fs::create_dir_all(&output_dir)
            .map_err(|e| format!("failed to create {}: {e}", output_dir.display()))?;
        if common.allow_write {
            let stamp_path = ctx
                .repo_root
                .join("docs")
                .join("_internal")
                .join("generated")
                .join("build-info.md");
            if let Some(parent) = stamp_path.parent() {
                fs::create_dir_all(parent).map_err(|e| {
                    format!("failed to create build stamp dir {}: {e}", parent.display())
                })?;
            }
            let commit = std::env::var("GITHUB_SHA").unwrap_or_else(|_| "local".to_string());
            let build_time = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|duration| duration.as_secs())
                .unwrap_or(0);
            fs::write(
                &stamp_path,
                format!(
                    "# Docs Build Info\n\n- Generated by: `bijux-dev-atlas docs build --allow-subprocess --allow-write`\n- Do not edit by hand: regenerate with the control-plane command.\n\n- Commit: `{commit}`\n- Build Unix Time: `{build_time}`\n- Site Output: `{}`\n",
                    site_paths.site_dir.display()
                ),
            )
            .map_err(|e| format!("failed to write build stamp {}: {e}", stamp_path.display()))?;
            let public_build_info_path = ctx
                .repo_root
                .join("docs")
                .join("reference")
                .join("build-info.md");
            fs::write(
                &public_build_info_path,
                format!(
                    "---\ntitle: Build Info\naudience: operator\ntype: reference\nstability: stable\nowner: docs-governance\nlast_reviewed: 2026-03-04\ntags:\n  - docs\n  - build\n  - release\n---\n\n# Docs Build Info\n\nThis page is regenerated by `bijux-dev-atlas docs build`.\n\n- Commit: `{commit}`\n- Build Unix Time: `{build_time}`\n- Site Output: `{}`\n",
                    site_paths.site_dir.display()
                ),
            )
            .map_err(|e| {
                format!(
                    "failed to write public build info {}: {e}",
                    public_build_info_path.display()
                )
            })?;
        }
    }
    let mut effective_args = args.to_vec();
    if label == "docs serve" {
        let mut attempts = 0u8;
        while attempts < 6 && !dev_addr_is_available(&effective_args) {
            if let Some(next) = bump_dev_addr_port(&effective_args) {
                effective_args = next;
            } else {
                break;
            }
            attempts += 1;
        }
    }
    let (stdout, stderr, code) = loop {
        let mut cmd = ProcessCommand::new("mkdocs");
        cmd.args(&effective_args).current_dir(&ctx.repo_root);
        if label == "docs serve" {
            let status = cmd
                .stdout(std::process::Stdio::inherit())
                .stderr(std::process::Stdio::inherit())
                .status()
                .map_err(|e| format!("failed to run mkdocs: {e}"))?;
            break (String::new(), String::new(), status.code().unwrap_or(1));
        }
        let out = cmd
            .output()
            .map_err(|e| format!("failed to run mkdocs: {e}"))?;
        let stdout = String::from_utf8_lossy(&out.stdout).to_string();
        let stderr = String::from_utf8_lossy(&out.stderr).to_string();
        let code = out.status.code().unwrap_or(1);
        break (stdout, stderr, code);
    };
    let mut files = Vec::<serde_json::Value>::new();
    if label == "docs build" && output_dir.exists() {
        for path in walk_files_local(&output_dir) {
            let Ok(bytes) = fs::read(&path) else { continue };
            let rel = path
                .strip_prefix(&output_dir)
                .unwrap_or(&path)
                .display()
                .to_string();
            let mut hasher = Sha256::new();
            hasher.update(&bytes);
            files.push(serde_json::json!({
                "path": rel,
                "sha256": format!("{:x}", hasher.finalize()),
                "bytes": bytes.len()
            }));
        }
        files.sort_by(|a, b| a["path"].as_str().cmp(&b["path"].as_str()));
        let index_path = ctx
            .artifacts_root
            .join("dist")
            .join("docs-site")
            .join(ctx.run_id.as_str())
            .join("build.index.json");
        if common.allow_write {
            if let Some(parent) = index_path.parent() {
                let _ = fs::create_dir_all(parent);
            }
            let _ = fs::write(
                &index_path,
                serde_json::to_string_pretty(&serde_json::json!({
                    "schema_version": 1,
                    "run_id": ctx.run_id.as_str(),
                    "files": files
                }))
                .unwrap_or_default(),
            );
        }
    }
    Ok((
        serde_json::json!({
            "schema_version":1,
            "run_id": ctx.run_id.as_str(),
            "error_code": if code == 0 { serde_json::Value::Null } else { serde_json::Value::String("DOCS_BUILD_ERROR".to_string()) },
            "text": format!("{label} {}", if code==0 {"ok"} else {"failed"}),
            "rows":[{"command": effective_args, "exit_code": code, "stdout": stdout, "stderr": stderr, "site_dir": output_dir.display().to_string(), "docs_dir": site_paths.docs_dir.display().to_string()}],
            "artifacts": {"site_dir": output_dir.display().to_string(), "build_index": ctx.artifacts_root.join("dist").join("docs-site").join(ctx.run_id.as_str()).join("build.index.json").display().to_string(), "files": files},
            "capabilities": {"subprocess": common.allow_subprocess, "fs_write": common.allow_write, "network": common.allow_network},
            "options": {"strict": common.strict, "include_drafts": common.include_drafts}
        }),
        code,
    ))
}

fn bump_dev_addr_port(args: &[String]) -> Option<Vec<String>> {
    let mut bumped = args.to_vec();
    let idx = bumped.iter().position(|v| v == "--dev-addr")?;
    let current = bumped.get(idx + 1)?.clone();
    let (host, port_str) = current.rsplit_once(':')?;
    let port = port_str.parse::<u16>().ok()?;
    let next_port = port.saturating_add(1);
    *bumped.get_mut(idx + 1)? = format!("{host}:{next_port}");
    Some(bumped)
}

fn dev_addr_is_available(args: &[String]) -> bool {
    let idx = match args.iter().position(|v| v == "--dev-addr") {
        Some(value) => value,
        None => return true,
    };
    let Some(addr) = args.get(idx + 1) else {
        return true;
    };
    std::net::TcpListener::bind(addr).is_ok()
}
