#!/usr/bin/env python3
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
contracts = ROOT / "docs" / "contracts"
out_gen = ROOT / "docs" / "contracts" / "generated"
out_gen.mkdir(parents=True, exist_ok=True)

error_codes = json.loads((contracts / "ERROR_CODES.json").read_text())["codes"]
metrics = json.loads((contracts / "METRICS.json").read_text())["metrics"]
endpoints = json.loads((contracts / "ENDPOINTS.json").read_text())["endpoints"]
chart_keys = json.loads((contracts / "CHART_VALUES.json").read_text())["top_level_keys"]

# rust generated constants
rust_path = ROOT / "crates" / "bijux-atlas-api" / "src" / "generated" / "error_codes.rs"
rust_path.parent.mkdir(parents=True, exist_ok=True)
rust = [
    "// @generated by scripts/contracts/generate_contract_artifacts.py",
    "pub const API_ERROR_CODES: &[&str] = &[",
]
for code in error_codes:
    rust.append(f'    "{code}",')
rust.append("];\n")
rust_path.write_text("\n".join(rust))

# markdown artifacts
(out_gen / "ERROR_CODES.md").write_text(
    "# Error Codes (Generated)\n\n" + "\n".join(f"- `{c}`" for c in error_codes) + "\n"
)
(out_gen / "METRICS.md").write_text(
    "# Metrics (Generated)\n\n"
    + "\n".join(
        f"- `{m['name']}` labels: {', '.join(m['labels'])}" for m in metrics
    )
    + "\n"
)
(out_gen / "ENDPOINTS.md").write_text(
    "# Endpoints (Generated)\n\n"
    + "\n".join(
        f"- `{e['method']} {e['path']}` telemetry: `{e['telemetry_class']}`"
        for e in endpoints
    )
    + "\n"
)
(out_gen / "CHART_VALUES.md").write_text(
    "# Chart Values Keys (Generated)\n\n"
    + "\n".join(f"- `{k}`" for k in chart_keys)
    + "\n"
)

# generated compatibility artifact for observability gate
obs_metrics_path = ROOT / "observability" / "metrics_contract.json"
obs_payload = {
    "schema_version": 1,
    "required_metrics": {m["name"]: m["labels"] for m in metrics},
    "required_spans": [
        "dataset resolve",
        "dataset download start",
        "sqlite_query",
        "serialize_response",
    ],
    "required_log_fields": ["request_id", "dataset"],
    "allowed_dynamic_labels": ["route", "status", "query_type", "stage", "code"],
}
obs_metrics_path.write_text(json.dumps(obs_payload, indent=2, sort_keys=True) + "\n")

print("contract artifacts generated")
