changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feat
        - feature
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Performance
      labels:
        - perf
    - title: CI and Tooling
      labels:
        - ci
        - chore
    - title: Documentation
      labels:
        - docs
    - title: Other
      labels:
        - "*"
