apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: bijux-atlas-slo-burn-alerts
  labels:
    subsystem: atlas
    contract_version: "1"
    contract_git_sha: "REQUIRED_AT_BUILD"
  annotations:
    contact: "ops@bijux.local"
    runbook_index: "docs/operations/runbooks/INDEX.md"
spec:
  groups:
  - name: bijux-atlas-slo-burn
    rules:
      - alert: BijuxAtlasCheapSloBurnFast
        expr: |
          (
            (
              sum(rate(http_requests_total{subsystem="atlas",class="cheap",status=~"5.."}[5m]))
              /
              clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="cheap"}[5m])), 1)
            ) / 0.0001
          ) > 14
          and
          (
            (
              sum(rate(http_requests_total{subsystem="atlas",class="cheap",status=~"5.."}[1h]))
              /
              clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="cheap"}[1h])), 1)
            ) / 0.0001
          ) > 14
        for: 5m
        labels:
          severity: page
          subsystem: atlas
          alert_contract_version: "1"
          owner: bijux-atlas-operations
          runbook_id: slo-cheap-burn
        annotations:
          summary: "Cheap class error budget burn is critically high"
          description: "Fast-burn condition (5m/1h) exceeded for cheap endpoint SLO."
          runbook: "docs/operations/runbooks/slo-cheap-burn.md"
      - alert: BijuxAtlasCheapSloBurnMedium
        expr: |
          (
            (
              sum(rate(http_requests_total{subsystem="atlas",class="cheap",status=~"5.."}[30m]))
              /
              clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="cheap"}[30m])), 1)
            ) / 0.0001
          ) > 6
          and
          (
            (
              sum(rate(http_requests_total{subsystem="atlas",class="cheap",status=~"5.."}[6h]))
              /
              clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="cheap"}[6h])), 1)
            ) / 0.0001
          ) > 6
        for: 15m
        labels:
          severity: page
          subsystem: atlas
          alert_contract_version: "1"
          owner: bijux-atlas-operations
          runbook_id: slo-cheap-burn
        annotations:
          summary: "Cheap class error budget burn is elevated"
          description: "Medium-burn condition (30m/6h) exceeded for cheap endpoint SLO."
          runbook: "docs/operations/runbooks/slo-cheap-burn.md"
      - alert: BijuxAtlasCheapSloBurnSlow
        expr: |
          (
            (
              sum(rate(http_requests_total{subsystem="atlas",class="cheap",status=~"5.."}[2h]))
              /
              clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="cheap"}[2h])), 1)
            ) / 0.0001
          ) > 3
          and
          (
            (
              sum(rate(http_requests_total{subsystem="atlas",class="cheap",status=~"5.."}[24h]))
              /
              clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="cheap"}[24h])), 1)
            ) / 0.0001
          ) > 3
        for: 30m
        labels:
          severity: warn
          subsystem: atlas
          alert_contract_version: "1"
          owner: bijux-atlas-operations
          runbook_id: slo-cheap-burn
        annotations:
          summary: "Cheap class error budget burn is slowly trending bad"
          description: "Slow-burn condition (2h/24h) exceeded for cheap endpoint SLO."
          runbook: "docs/operations/runbooks/slo-cheap-burn.md"
      - alert: BijuxAtlasStandardSloBurnFast
        expr: |
          (
            (
              sum(rate(http_requests_total{subsystem="atlas",class="standard",status=~"5.."}[5m]))
              /
              clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="standard"}[5m])), 1)
            ) / 0.001
          ) > 14
          and
          (
            (
              sum(rate(http_requests_total{subsystem="atlas",class="standard",status=~"5.."}[1h]))
              /
              clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="standard"}[1h])), 1)
            ) / 0.001
          ) > 14
        for: 5m
        labels:
          severity: page
          subsystem: atlas
          alert_contract_version: "1"
          owner: bijux-atlas-operations
          runbook_id: slo-standard-burn
        annotations:
          summary: "Standard class error budget burn is critically high"
          description: "Fast-burn condition (5m/1h) exceeded for standard endpoint SLO."
          runbook: "docs/operations/runbooks/slo-standard-burn.md"
      - alert: BijuxAtlasStandardSloBurnMedium
        expr: |
          (
            (
              sum(rate(http_requests_total{subsystem="atlas",class="standard",status=~"5.."}[30m]))
              /
              clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="standard"}[30m])), 1)
            ) / 0.001
          ) > 6
          and
          (
            (
              sum(rate(http_requests_total{subsystem="atlas",class="standard",status=~"5.."}[6h]))
              /
              clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="standard"}[6h])), 1)
            ) / 0.001
          ) > 6
        for: 15m
        labels:
          severity: page
          subsystem: atlas
          alert_contract_version: "1"
          owner: bijux-atlas-operations
          runbook_id: slo-standard-burn
        annotations:
          summary: "Standard class error budget burn is elevated"
          description: "Medium-burn condition (30m/6h) exceeded for standard endpoint SLO."
          runbook: "docs/operations/runbooks/slo-standard-burn.md"
      - alert: BijuxAtlasStandardSloBurnSlow
        expr: |
          (
            (
              sum(rate(http_requests_total{subsystem="atlas",class="standard",status=~"5.."}[2h]))
              /
              clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="standard"}[2h])), 1)
            ) / 0.001
          ) > 3
          and
          (
            (
              sum(rate(http_requests_total{subsystem="atlas",class="standard",status=~"5.."}[24h]))
              /
              clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="standard"}[24h])), 1)
            ) / 0.001
          ) > 3
        for: 30m
        labels:
          severity: warn
          subsystem: atlas
          alert_contract_version: "1"
          owner: bijux-atlas-operations
          runbook_id: slo-standard-burn
        annotations:
          summary: "Standard class error budget burn is slowly trending bad"
          description: "Slow-burn condition (2h/24h) exceeded for standard endpoint SLO."
          runbook: "docs/operations/runbooks/slo-standard-burn.md"
      - alert: BijuxAtlasOverloadSurvivalViolated
        expr: |
          (
            sum(rate(http_requests_total{subsystem="atlas",class="cheap",status=~"2.."}[5m]))
            /
            clamp_min(sum(rate(http_requests_total{subsystem="atlas",class="cheap"}[5m])), 1)
          ) < 0.9999
          and avg_over_time(atlas_overload_active{subsystem="atlas"}[5m]) > 0
        for: 5m
        labels:
          severity: page
          subsystem: atlas
          alert_contract_version: "1"
          owner: bijux-atlas-operations
          runbook_id: slo-overload-survival
        annotations:
          summary: "Cheap endpoint survival SLO violated during overload"
          description: "Cheap endpoint success dropped below 99.99% while overload shedding was active."
          runbook: "docs/operations/runbooks/slo-overload-survival.md"
      - alert: BijuxAtlasRegistryRefreshStale
        expr: atlas_registry_refresh_age_seconds{subsystem="atlas"} > 600
        for: 15m
        labels:
          severity: warn
          subsystem: atlas
          alert_contract_version: "1"
          owner: bijux-atlas-operations
          runbook_id: slo-registry-refresh-stale
        annotations:
          summary: "Registry refresh is stale"
          description: "Registry refresh age exceeded 10 minutes for 15 minutes."
          runbook: "docs/operations/runbooks/slo-registry-refresh-stale.md"
      - alert: BijuxAtlasStoreBackendErrorSpike
        expr: |
          sum(rate(atlas_store_errors_total{subsystem="atlas"}[5m]))
          /
          clamp_min(sum(rate(http_requests_total{subsystem="atlas",class=~"standard|heavy"}[5m])), 1)
          > 0.02
        for: 10m
        labels:
          severity: page
          subsystem: atlas
          alert_contract_version: "1"
          owner: bijux-atlas-operations
          runbook_id: slo-store-backend-error-spike
        annotations:
          summary: "Store backend error spike"
          description: "Store backend errors crossed 2% of standard/heavy request volume over 10m."
          runbook: "docs/operations/runbooks/slo-store-backend-error-spike.md"
