from __future__ import annotations

from ....core.base import CheckCategory, CheckDef
from .check_registry_change_gates import (
    check_registry_change_requires_docs_update,
    check_registry_change_requires_golden_update,
    check_registry_change_requires_owner_update,
)
from .check_registry_integrity import (
    check_registry_all_checks_have_canonical_id,
    check_registry_canonical_id_matches_module_path,
    check_registry_docs_link_required,
    check_registry_docs_meta_matches_runtime,
    check_registry_integrity,
    check_registry_no_duplicate_canonical_id,
    check_registry_owners_required,
    check_registry_remediation_link_required,
    check_registry_speed_required,
    check_registry_suite_membership_required,
)


CHECKS = (
    CheckDef(
        "checks.registry_integrity",
        "checks",
        "validate checks registry TOML/JSON integrity and drift",
        2500,
        check_registry_integrity,
        category=CheckCategory.CONTRACT,
        fix_hint="Run `./bin/atlasctl gen checks-registry` and commit REGISTRY.toml/REGISTRY.generated.json.",
        slow=True,
        owners=("platform",),
        tags=("checks", "registry"),
    ),
    CheckDef(
        "checks.registry_change_owners_gate",
        "checks",
        "require ownership metadata update when checks registry changes",
        500,
        check_registry_change_requires_owner_update,
        category=CheckCategory.POLICY,
        fix_hint="Update makefiles/ownership.json when REGISTRY.toml changes.",
        owners=("platform",),
        tags=("checks", "registry", "ci"),
    ),
    CheckDef(
        "checks.registry_change_docs_gate",
        "checks",
        "require docs update when checks registry changes",
        500,
        check_registry_change_requires_docs_update,
        category=CheckCategory.POLICY,
        fix_hint="Update docs/checks/registry.md when REGISTRY.toml changes.",
        owners=("platform",),
        tags=("checks", "registry", "ci"),
    ),
    CheckDef(
        "checks.registry_change_goldens_gate",
        "checks",
        "require checks list/tree/owners goldens update when registry changes",
        500,
        check_registry_change_requires_golden_update,
        category=CheckCategory.POLICY,
        fix_hint="Refresh check list/tree/owners goldens when REGISTRY.toml changes.",
        owners=("platform",),
        tags=("checks", "registry", "ci"),
    ),
    CheckDef(
        "checks.registry_all_checks_have_canonical_id",
        "checks",
        "require every registered check to expose a canonical checks_* id",
        700,
        check_registry_all_checks_have_canonical_id,
        category=CheckCategory.CONTRACT,
        fix_hint="Update REGISTRY.toml ids to checks_<domain>_<area>_<name>.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_no_duplicate_canonical_id",
        "checks",
        "forbid duplicate canonical check ids in registry",
        700,
        check_registry_no_duplicate_canonical_id,
        category=CheckCategory.CONTRACT,
        fix_hint="Deduplicate conflicting ids in REGISTRY.toml.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_canonical_id_matches_module_path",
        "checks",
        "require canonical id domain/area segments to match implementation module path",
        900,
        check_registry_canonical_id_matches_module_path,
        category=CheckCategory.POLICY,
        fix_hint="Align check module paths with canonical check id segments.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_owners_required",
        "checks",
        "require every registry entry to declare an owner",
        500,
        check_registry_owners_required,
        category=CheckCategory.CONTRACT,
        fix_hint="Add owner field to registry entries.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_speed_required",
        "checks",
        "require speed classification for every registry entry (fast|slow|nightly)",
        500,
        check_registry_speed_required,
        category=CheckCategory.CONTRACT,
        fix_hint="Set speed to fast, slow, or nightly in REGISTRY.toml.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_suite_membership_required",
        "checks",
        "require every registry check to be selected by at least one suite manifest",
        900,
        check_registry_suite_membership_required,
        category=CheckCategory.POLICY,
        fix_hint="Add unassigned checks to at least one suite in registry/suites_catalog.json.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_docs_link_required",
        "checks",
        "require docs_link metadata for every registry check entry",
        700,
        check_registry_docs_link_required,
        category=CheckCategory.CONTRACT,
        fix_hint="Set docs_link to an existing documentation page in checks catalog generation.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_remediation_link_required",
        "checks",
        "require remediation_link metadata for every registry check entry",
        700,
        check_registry_remediation_link_required,
        category=CheckCategory.CONTRACT,
        fix_hint="Set remediation_link to an existing remediation playbook page.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_docs_meta_runtime_drift",
        "checks",
        "require generated docs _meta checks registry file to match runtime registry",
        700,
        check_registry_docs_meta_matches_runtime,
        category=CheckCategory.DRIFT,
        fix_hint="Run `./bin/atlasctl gen checks-registry` and commit docs/_meta/checks-registry.txt.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
)
