from __future__ import annotations

from ....model import CheckCategory, CheckDef
from .check_registry_change_gates import (
    check_registry_change_requires_docs_update,
    check_registry_change_requires_golden_update,
    check_registry_change_requires_owner_update,
)
from .check_registry_integrity import (
    check_count_budget,
    check_checks_domains_module_budget,
    check_checks_module_loc_budget,
    check_checks_root_entry_budget,
    check_checks_tools_module_budget,
    check_docs_index_complete,
    check_owners_ssot,
    check_registry_no_banned_adjectives_in_ids,
    check_registry_transition_complete,
    check_registry_all_checks_have_canonical_id,
    check_registry_canonical_id_matches_module_path,
    check_registry_docs_link_required,
    check_registry_docs_meta_matches_runtime,
    check_registry_integrity,
    check_registry_no_duplicate_canonical_id,
    check_registry_owners_required,
    check_registry_remediation_link_required,
    check_registry_speed_required,
    check_registry_suite_membership_required,
    check_remediation_ssot,
    check_surfaces_no_banned_adjectives_in_paths,
    check_structured_results_legacy_signature_budget,
    check_suites_inventory_ssot,
    check_suites_no_orphans,
)


CHECKS = (
    CheckDef(
        "checks.registry_integrity",
        "checks",
        "validate checks registry TOML/JSON integrity and drift",
        2500,
        check_registry_integrity,
        category=CheckCategory.CONTRACT,
        fix_hint="Run `./bin/atlasctl gen checks-registry` and commit REGISTRY.toml/REGISTRY.generated.json.",
        slow=True,
        owners=("platform",),
        tags=("checks", "registry"),
    ),
    CheckDef(
        "checks.registry_change_owners_gate",
        "checks",
        "require ownership metadata update when checks registry changes",
        500,
        check_registry_change_requires_owner_update,
        category=CheckCategory.POLICY,
        fix_hint="Update configs/make/ownership.json when REGISTRY.toml changes.",
        owners=("platform",),
        tags=("checks", "registry", "ci"),
    ),
    CheckDef(
        "checks.registry_change_docs_gate",
        "checks",
        "require docs update when checks registry changes",
        500,
        check_registry_change_requires_docs_update,
        category=CheckCategory.POLICY,
        fix_hint="Update docs/checks/registry.md when REGISTRY.toml changes.",
        owners=("platform",),
        tags=("checks", "registry", "ci"),
    ),
    CheckDef(
        "checks.registry_change_goldens_gate",
        "checks",
        "require checks list/tree/owners goldens update when registry changes",
        500,
        check_registry_change_requires_golden_update,
        category=CheckCategory.POLICY,
        fix_hint="Refresh check list/tree/owners goldens when REGISTRY.toml changes.",
        owners=("platform",),
        tags=("checks", "registry", "ci"),
    ),
    CheckDef(
        "checks.registry_all_checks_have_canonical_id",
        "checks",
        "require every registered check to expose a canonical checks_* id",
        700,
        check_registry_all_checks_have_canonical_id,
        category=CheckCategory.CONTRACT,
        fix_hint="Update REGISTRY.toml ids to checks_<domain>_<area>_<name>.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_no_duplicate_canonical_id",
        "checks",
        "forbid duplicate canonical check ids in registry",
        700,
        check_registry_no_duplicate_canonical_id,
        category=CheckCategory.CONTRACT,
        fix_hint="Deduplicate conflicting ids in REGISTRY.toml.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_canonical_id_matches_module_path",
        "checks",
        "require canonical id domain/area segments to match implementation module path",
        900,
        check_registry_canonical_id_matches_module_path,
        category=CheckCategory.POLICY,
        fix_hint="Align check module paths with canonical check id segments.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_owners_required",
        "checks",
        "require every registry entry to declare an owner",
        500,
        check_registry_owners_required,
        category=CheckCategory.CONTRACT,
        fix_hint="Add owner field to registry entries.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_speed_required",
        "checks",
        "require speed classification for every registry entry (fast|slow|nightly)",
        500,
        check_registry_speed_required,
        category=CheckCategory.CONTRACT,
        fix_hint="Set speed to fast, slow, or nightly in REGISTRY.toml.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_suite_membership_required",
        "checks",
        "require every registry check to be selected by at least one suite manifest",
        900,
        check_registry_suite_membership_required,
        category=CheckCategory.POLICY,
        fix_hint="Add unassigned checks to at least one suite in registry/suites_catalog.json.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_docs_link_required",
        "checks",
        "require docs_link metadata for every registry check entry",
        700,
        check_registry_docs_link_required,
        category=CheckCategory.CONTRACT,
        fix_hint="Set docs_link to an existing documentation page in checks catalog generation.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_remediation_link_required",
        "checks",
        "require remediation_link metadata for every registry check entry",
        700,
        check_registry_remediation_link_required,
        category=CheckCategory.CONTRACT,
        fix_hint="Set remediation_link to an existing remediation playbook page.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_docs_meta_runtime_drift",
        "checks",
        "require generated docs _meta checks registry file to match runtime registry",
        700,
        check_registry_docs_meta_matches_runtime,
        category=CheckCategory.DRIFT,
        fix_hint="Run `./bin/atlasctl gen checks-registry` and commit docs/_meta/checks-registry.txt.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.registry_transition_complete",
        "checks",
        "fail when check-id migration aliases remain after transition deadline",
        700,
        check_registry_transition_complete,
        category=CheckCategory.POLICY,
        fix_hint="Clear configs/policy/check-id-migration.json aliases after deadline or extend with explicit policy.",
        owners=("platform",),
        tags=("checks", "registry", "required"),
    ),
    CheckDef(
        "checks.suites_inventory_ssot",
        "checks",
        "require deterministic suite inventory in suite registry SSOT",
        700,
        check_suites_inventory_ssot,
        category=CheckCategory.CONTRACT,
        fix_hint="Sort suite names and remove duplicates in registry/suites_catalog.json.",
        owners=("platform",),
        tags=("checks", "suite", "required"),
    ),
    CheckDef(
        "checks.suites_no_orphans",
        "checks",
        "require every registered check to belong to at least one suite",
        700,
        check_suites_no_orphans,
        category=CheckCategory.POLICY,
        fix_hint="Add orphan checks to suite registry manifests.",
        owners=("platform",),
        tags=("checks", "suite", "required"),
    ),
    CheckDef(
        "checks.owners_ssot",
        "checks",
        "require every check entry to have an owner in SSOT registry",
        500,
        check_owners_ssot,
        category=CheckCategory.CONTRACT,
        fix_hint="Set owners for every check in REGISTRY.toml.",
        owners=("platform",),
        tags=("checks", "required"),
    ),
    CheckDef(
        "checks.remediation_ssot",
        "checks",
        "require every check entry to have remediation documentation link",
        500,
        check_remediation_ssot,
        category=CheckCategory.CONTRACT,
        fix_hint="Set remediation_link for every check in checks catalog generation.",
        owners=("platform",),
        tags=("checks", "required"),
    ),
    CheckDef(
        "checks.docs_index_complete",
        "checks",
        "require checks docs index to include canonical check ids",
        700,
        check_docs_index_complete,
        category=CheckCategory.DRIFT,
        fix_hint="Regenerate/update packages/atlasctl/docs/checks/index.md with full canonical inventory.",
        owners=("platform",),
        tags=("checks", "docs", "required"),
    ),
    CheckDef(
        "checks.count_budget",
        "checks",
        "enforce checks-count ratchet budget from configs/policy/checks-count-budget.json",
        500,
        check_count_budget,
        category=CheckCategory.POLICY,
        fix_hint="Reduce checks count or intentionally raise budget in configs/policy/checks-count-budget.json.",
        owners=("platform",),
        tags=("checks", "required"),
    ),
    CheckDef(
        "checks.root_entry_budget",
        "checks",
        "enforce checks root entry budget",
        500,
        check_checks_root_entry_budget,
        category=CheckCategory.POLICY,
        fix_hint="Reduce top-level entries under packages/atlasctl/src/atlasctl/checks or adjust policy budget intentionally.",
        owners=("platform",),
        tags=("checks", "required"),
    ),
    CheckDef(
        "checks.domains_module_budget",
        "checks",
        "enforce checks domains module budget",
        500,
        check_checks_domains_module_budget,
        category=CheckCategory.POLICY,
        fix_hint="Keep checks domain module count within budget or adjust policy budget intentionally.",
        owners=("platform",),
        tags=("checks", "required"),
    ),
    CheckDef(
        "checks.tools_module_budget",
        "checks",
        "enforce checks tools module budget",
        500,
        check_checks_tools_module_budget,
        category=CheckCategory.POLICY,
        fix_hint="Keep checks tools module count within budget or adjust policy budget intentionally.",
        owners=("platform",),
        tags=("checks", "required"),
    ),
    CheckDef(
        "checks.module_loc_budget",
        "checks",
        "enforce checks module loc budget",
        600,
        check_checks_module_loc_budget,
        category=CheckCategory.POLICY,
        fix_hint="Split oversized checks modules into intent-focused modules.",
        owners=("platform",),
        tags=("checks", "required"),
    ),
    CheckDef(
        "checks.structured_results_legacy_signature_budget",
        "checks",
        "ratchet down legacy tuple check signatures in favor of structured results",
        600,
        check_structured_results_legacy_signature_budget,
        category=CheckCategory.POLICY,
        fix_hint="Migrate tuple[int, list[str]] check signatures to structured Violation/CheckOutcome results.",
        owners=("platform",),
        tags=("checks", "required"),
    ),
    CheckDef(
        "checks.registry_no_banned_adjectives_in_ids",
        "checks",
        "forbid policy-listed adjectives in canonical check ids",
        500,
        check_registry_no_banned_adjectives_in_ids,
        category=CheckCategory.POLICY,
        fix_hint="Rename check ids to remove policy-listed adjectives.",
        owners=("platform",),
        tags=("checks", "required"),
    ),
    CheckDef(
        "checks.surfaces_no_banned_adjectives_in_paths",
        "checks",
        "forbid policy-listed adjectives in atlasctl module/docs path names",
        500,
        check_surfaces_no_banned_adjectives_in_paths,
        category=CheckCategory.POLICY,
        fix_hint="Rename atlasctl source/docs files and directories to remove banned adjectives.",
        owners=("platform",),
        tags=("checks", "required"),
    ),
)
