#!/usr/bin/env python3
"""Render a lifecycle summary markdown table from a JSON report."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def render_table(summary: dict) -> str:
    rows = summary.get("profiles", [])
    lines = [
        "<!-- Generated by scripts/docs/generate_lifecycle_summary_table.py. Do not edit by hand. -->",
        "",
        "# Lifecycle Summary Table",
        "",
        "| Profile | Namespace | Upgrade | Rollback |",
        "| --- | --- | --- | --- |",
    ]
    for row in sorted(rows, key=lambda item: item.get("profile", "")):
        lines.append(
            "| {profile} | {namespace} | {upgrade} | {rollback} |".format(
                profile=row.get("profile", ""),
                namespace=row.get("namespace", ""),
                upgrade=row.get("upgrade_status", "not-run"),
                rollback=row.get("rollback_status", "not-run"),
            )
        )
    if not rows:
        lines.append("| none | none | not-run | not-run |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Path to ops-lifecycle-summary.json")
    parser.add_argument("--output", required=True, help="Path to markdown output")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    if input_path.exists():
        payload = json.loads(input_path.read_text())
    else:
        payload = {"profiles": []}

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_table(payload))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
