#!/usr/bin/env python3
"""Generate docs health diagnostics as a committed markdown page."""

from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path
from urllib.parse import urlparse


REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_ROOT = REPO_ROOT / "docs"
OUTPUT_PATH = DOCS_ROOT / "_internal" / "generated" / "docs-health-dashboard.md"
ALLOWLIST_PATH = REPO_ROOT / "configs" / "docs" / "external-link-allowlist.json"
CURRENT_SHA = "240605bb1dd034f0f58f07a313d49d280f81556c"
LINK_RE = re.compile(r"\[[^\]]+\]\(([^)]+)\)")


def iter_docs() -> list[Path]:
    return sorted(DOCS_ROOT.rglob("*.md"))


def external_urls(text: str) -> list[str]:
    urls = []
    for match in LINK_RE.finditer(text):
        target = match.group(1)
        if target.startswith("http://") or target.startswith("https://"):
            urls.append(target)
    return urls


def local_targets(text: str, source: Path) -> set[str]:
    targets: set[str] = set()
    for match in LINK_RE.finditer(text):
        target = match.group(1)
        if target.startswith(("http://", "https://", "#", "mailto:")):
            continue
        target_path = target.split("#", 1)[0]
        if not target_path:
            continue
        resolved = (source.parent / target_path).resolve()
        try:
            relative = resolved.relative_to(REPO_ROOT)
        except ValueError:
            continue
        if relative.suffix == "":
            index_md = relative / "index.md"
            if (REPO_ROOT / index_md).exists():
                relative = index_md
        targets.add(str(relative))
    return targets


def main() -> None:
    docs_files = iter_docs()
    allowlist = json.loads(ALLOWLIST_PATH.read_text())
    allowed_domains = set(allowlist.get("allowed_domains", []))

    external = []
    linked_local: set[str] = set()
    missing_verified = []
    page_lengths = []
    single_line_offenders = []

    for path in docs_files:
        text = path.read_text()
        lines = text.splitlines()
        external.extend(external_urls(text))
        linked_local.update(local_targets(text, path))
        if "Last verified against:" not in text:
            missing_verified.append(str(path.relative_to(REPO_ROOT)))
        page_lengths.append((len(lines), str(path.relative_to(REPO_ROOT))))
        longest_line = max((len(line) for line in lines), default=0)
        if longest_line > 140:
            single_line_offenders.append((longest_line, str(path.relative_to(REPO_ROOT))))

    domains = [urlparse(url).netloc for url in external]
    unique_domains = sorted(set(domains))
    covered_domains = sorted(domain for domain in unique_domains if domain in allowed_domains)

    orphan_pages = []
    for path in docs_files:
        rel = str(path.relative_to(REPO_ROOT))
        if "/_internal/" in rel or rel.endswith("index.md") or rel == "docs/start-here.md":
            continue
        if rel not in linked_local:
            orphan_pages.append(rel)

    top_pages = sorted(page_lengths, reverse=True)[:10]
    top_single_line = sorted(single_line_offenders, reverse=True)[:10]

    lines = [
        "# Docs Health Dashboard",
        "",
        "- Owner: `docs-governance`",
        "- Review cadence: `quarterly`",
        "- Type: `generated`",
        "- Audience: `contributor`",
        "- Stability: `stable`",
        f"- Last verified against: `main@{CURRENT_SHA}`",
        "- Generated by: `scripts/docs/generate_docs_health_dashboard.py`",
        "- Do not edit by hand: rerun the generator.",
        "",
        "## Summary",
        "",
        f"- External links: `{len(external)}`",
        f"- Unique external domains: `{len(unique_domains)}`",
        f"- Allowlist-covered external domains: `{len(covered_domains)}/{len(unique_domains)}`",
        f"- Orphan pages: `{len(orphan_pages)}`",
        f"- Pages missing `Last verified against`: `{len(missing_verified)}`",
        "",
        "## External Link Domains",
        "",
    ]
    for domain, count in sorted(Counter(domains).items()):
        marker = "allowlisted" if domain in allowed_domains else "not allowlisted"
        lines.append(f"- `{domain}`: `{count}` links, `{marker}`")

    lines.extend([
        "",
        "## Longest Pages",
        "",
    ])
    for length, path in top_pages:
        lines.append(f"- `{path}`: `{length}` lines")

    lines.extend([
        "",
        "## Single-Line Offenders",
        "",
    ])
    for length, path in top_single_line:
        lines.append(f"- `{path}`: longest line `{length}` characters")
    if not top_single_line:
        lines.append("- None")

    lines.extend([
        "",
        "## Missing Verification Markers",
        "",
    ])
    for path in missing_verified[:20]:
        lines.append(f"- `{path}`")
    if not missing_verified:
        lines.append("- None")

    lines.extend([
        "",
        "## Orphan Pages",
        "",
    ])
    for path in orphan_pages[:20]:
        lines.append(f"- `{path}`")
    if not orphan_pages:
        lines.append("- None")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
