#!/usr/bin/env python3
"""Generate docs/reference/repo-map.md from the current repository layout."""

from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "docs" / "reference" / "repo-map.md"
MAX_DEPTH = 2
IGNORE = {
    ".git",
    ".idea",
    "artifacts",
    "target",
    ".venv",
    "__pycache__",
}
SSOT = [
    "ops/k8s/charts/bijux-atlas/values.yaml",
    "ops/k8s/values/profiles.json",
    "ops/k8s/rollout-safety-contract.json",
    "docs/redirects.json",
    "mkdocs.yml",
]
DANGEROUS = [
    "mkdocs.yml",
    "ops/k8s/charts/bijux-atlas/templates/",
    "ops/k8s/charts/bijux-atlas/values.schema.json",
    "ops/k8s/install-matrix.json",
]
GENERATED = [
    "docs/_internal/generated/",
    "docs/reference/repo-map.md",
    "ops/_examples/networkpolicy/",
]


def iter_tree(path: Path, prefix: str = "", depth: int = 0) -> list[str]:
    if depth > MAX_DEPTH:
        return []
    entries = []
    for child in sorted(path.iterdir(), key=lambda p: p.name):
        if child.name in IGNORE:
            continue
        label = child.name + ("/" if child.is_dir() else "")
        entries.append(f"{prefix}- `{label}`")
        if child.is_dir() and depth < MAX_DEPTH:
            entries.extend(iter_tree(child, prefix + "  ", depth + 1))
    return entries


def render_list(items: list[str]) -> str:
    return "\n".join(f"- `{item}`" for item in items)


def main() -> None:
    lines = [
        "# Repository Map",
        "",
        "- Owner: `bijux-atlas-operations`",
        "- Type: `reference`",
        "- Audience: `contributor`",
        "- Stability: `stable`",
        "- Last verified against: `main@fc2319a8483a4d0c9d08e5227ec31d7cb6677c4a`",
        "- Generated by: `scripts/docs/generate_repo_map.py`",
        "- Do not edit by hand: rerun the generator.",
        "",
        "## Purpose",
        "",
        "This generated page gives a bounded filesystem view and highlights the canonical surfaces",
        "that need extra care during repository changes.",
        "",
        "## Tree Summary",
        "",
        *iter_tree(REPO_ROOT),
        "",
        "## SSOT Surfaces",
        "",
        render_list(SSOT),
        "",
        "## Dangerous Surfaces",
        "",
        render_list(DANGEROUS),
        "",
        "## Generated Surfaces",
        "",
        render_list(GENERATED),
        "",
        "## Edit Policy",
        "",
        "- Changes to SSOT surfaces require governance review before merge.",
        "- Changes that add new generated surfaces must update `docs/reference/generated-artifacts.md`.",
        "- Changes that move canonical directories must also update `docs/development/repo-layout.md`.",
    ]
    OUTPUT_PATH.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
