#!/usr/bin/env python3
# Purpose: generate repository naming inventory for docs/scripts/tests/load suites.
# Inputs: tracked files from git and docs contract sources.
# Outputs: docs/_generated/naming-inventory.md
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "_generated" / "naming-inventory.md"
SUITES = ROOT / "ops" / "load" / "suites" / "suites.json"
RUNBOOKS = ROOT / "docs" / "operations" / "runbooks"
RUNBOOK_MAP = ROOT / "docs" / "operations" / "observability" / "runbook-dashboard-alert-map.md"

FORBIDDEN = ("phase", "task", "stage", "round", "iteration", "tmp", "placeholder")
DOC_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*\.md$")
SCRIPT_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*\.(sh|py)$")


def tracked_files() -> list[str]:
    out = subprocess.check_output(["git", "ls-files"], cwd=ROOT, text=True)
    return [line.strip() for line in out.splitlines() if line.strip()]


def has_forbidden_token(path: str) -> bool:
    stem = Path(path).stem.lower()
    return any(token in stem for token in FORBIDDEN)


def runbook_rows() -> int:
    text = RUNBOOK_MAP.read_text(encoding="utf-8")
    return sum(1 for line in text.splitlines() if line.startswith("| `") and line.endswith("|"))


def main() -> int:
    files = tracked_files()
    docs = [p for p in files if p.startswith("docs/") and p.endswith(".md")]
    scripts = [p for p in files if p.startswith("scripts/") and p.endswith((".sh", ".py"))]
    rust_tests = [p for p in files if p.endswith(".rs") and "/tests/" in p]
    load_suites = json.loads(SUITES.read_text(encoding="utf-8"))["suites"]
    runbooks = sorted([p.name for p in RUNBOOKS.glob("*.md") if p.name != "INDEX.md"])

    doc_non_kebab = [
        p
        for p in docs
        if Path(p).name not in {"INDEX.md", "STYLE.md", "README.md", "COMPATIBILITY.md", "DEPRECATION.md", "V1_SURFACE.md"}
        and not p.startswith("docs/_generated/contracts/")
        and not DOC_RE.match(Path(p).name)
    ]
    script_non_kebab = [p for p in scripts if not SCRIPT_RE.match(Path(p).name)]
    forbidden = [p for p in files if has_forbidden_token(p)]

    lines = [
        "# Naming Inventory",
        "",
        "- Owner: `docs-governance`",
        "- Generated by: `scripts/docs/naming_inventory.py`",
        "",
        "## Summary",
        "",
        f"- Tracked files: `{len(files)}`",
        f"- Docs markdown files: `{len(docs)}`",
        f"- Script files under `scripts/`: `{len(scripts)}`",
        f"- Rust test files: `{len(rust_tests)}`",
        f"- Load suites in `ops/load/suites/suites.json`: `{len(load_suites)}`",
        f"- Runbooks in `docs/operations/runbooks/`: `{len(runbooks)}`",
        f"- Runbook map rows: `{runbook_rows()}`",
        "",
        "## Naming Health",
        "",
        f"- Forbidden-token hits: `{len(forbidden)}`",
        f"- Non-kebab docs outside allowed exceptions: `{len(doc_non_kebab)}`",
        f"- Non-kebab scripts under `scripts/`: `{len(script_non_kebab)}`",
        "",
        "## Load Suites",
        "",
    ]
    for suite in sorted(load_suites, key=lambda item: item["name"]):
        lines.append(f"- `{suite['name']}`")
    lines.extend(["", "## Runbooks", ""])
    for name in runbooks:
        lines.append(f"- `{name}`")
    lines.extend(["", "## Violations", ""])
    if not forbidden and not doc_non_kebab and not script_non_kebab:
        lines.append("None.")
    else:
        for entry in sorted(set(forbidden + doc_non_kebab + script_non_kebab)):
            lines.append(f"- `{entry}`")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(OUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
