from __future__ import annotations

import argparse

def configure_suite_parser(sub: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    parser = sub.add_parser("suite", help="run atlasctl named suites")
    parser.add_argument("--list", dest="list_suites", action="store_true", help="list configured suites")
    parser.add_argument("--json", action="store_true", help="emit machine-readable JSON output")
    suite_sub = parser.add_subparsers(dest="suite_cmd", required=False)

    suite_list = suite_sub.add_parser("list", help="list configured suites")
    suite_list.add_argument("--json", action="store_true")
    suite_list.add_argument("--by-group", action="store_true", help="group suites by marker")
    coverage = suite_sub.add_parser("coverage", help="show check-to-suite coverage")
    coverage.add_argument("--json", action="store_true")
    suite_check = suite_sub.add_parser("check", help="validate suite inventory/tag coverage policy")
    suite_check.add_argument("--json", action="store_true")

    run = suite_sub.add_parser("run", help="run a configured suite")
    run.add_argument("name", nargs="?", help="suite name (defaults to configured default)")
    run.add_argument("--json", action="store_true", help="emit machine-readable results")
    run.add_argument("--report", choices=["text", "json"], help="output format alias for suite results")
    run.add_argument("--junit", help="write junit xml report")
    run.add_argument("--list", action="store_true", help="list expanded tasks without running")
    run.add_argument("--dry-run", action="store_true", help="print tasks without executing")
    run.add_argument("--only", action="append", default=[], help="glob pattern to include task labels")
    run.add_argument("--skip", action="append", default=[], help="glob pattern to skip task labels")
    run.add_argument("--group", action="append", default=[], help="restrict tasks/checks to logical group tags (e.g. ops, fast, slow)")
    run.add_argument("--target-dir", help="suite output directory")
    run.add_argument("--show-output", action="store_true", help="stream command task output")
    run.add_argument("--pytest-q", action="store_true", help="pytest-style quiet progress and summary output")
    run.add_argument("--slow-threshold-ms", type=int, default=1000, help="threshold for slow suite items report")
    run.add_argument("--slow-report", help="write slow suite items report path")
    run.add_argument("--profile", action="store_true", help="emit suite performance profile artifact")
    run.add_argument("--maxfail", type=int, default=0, help="stop after N failing tasks (0 disables)")
    group = run.add_mutually_exclusive_group()
    group.add_argument("--fail-fast", action="store_true", help="stop at first failure")
    group.add_argument("--keep-going", action="store_true", help="continue through all tasks (default)")
    explain = suite_sub.add_parser("explain", help="explain suite tasks and rationale")
    explain.add_argument("name", nargs="?")
    explain.add_argument("--json", action="store_true")
    doctor = suite_sub.add_parser("doctor", help="suggest next actions from a suite run")
    doctor.add_argument("--run-id", help="run id to inspect")
    doctor.add_argument("--json", action="store_true")
    artifacts = suite_sub.add_parser("artifacts", help="print suite artifact locations")
    artifacts.add_argument("--run-id", help="run id to inspect")
    artifacts.add_argument("--json", action="store_true")
    diff = suite_sub.add_parser("diff", help="diff two suite runs")
    diff.add_argument("run1")
    diff.add_argument("run2")
    diff.add_argument("--json", action="store_true")

    for suite_name in ("docs", "dev", "ops", "policies", "configs", "local", "repo-hygiene", "lint-fast", "lint-all", "checks-fast", "checks-all", "control-plane-gates", "ops-run-guardrails", "bypass-governance", "slow", "required", "ci", "required_proof", "all"):
        sp = suite_sub.add_parser(suite_name, help=f"run first-class `{suite_name}` suite")
        sp.add_argument("--json", action="store_true", help="emit machine-readable results")
        sp.add_argument("--report", choices=["text", "json"], help="output format alias for suite results")
        sp.add_argument("--list", action="store_true", help="list suite checks only")
        sp.add_argument("--dry-run", action="store_true", help="print checks without executing")
        sp.add_argument("--group", action="append", default=[], help="restrict checks to logical group tags (e.g. ops, fast, slow)")
        sp.add_argument("--target-dir", help="suite output directory")
    internal = suite_sub.add_parser("internal", help="run first-class `internal` suite (requires ATLASCTL_INTERNAL=1)")
    internal.add_argument("--json", action="store_true", help="emit machine-readable results")
    internal.add_argument("--report", choices=["text", "json"], help="output format alias for suite results")
    internal.add_argument("--list", action="store_true", help="list suite checks only")
    internal.add_argument("--dry-run", action="store_true", help="print checks without executing")
    internal.add_argument("--group", action="append", default=[], help="restrict checks to logical group tags (e.g. ops, fast, slow)")
    internal.add_argument("--target-dir", help="suite output directory")
