from __future__ import annotations

from .native import (
    check_docs_no_ops_generated_run_paths,
    check_duplicate_script_names,
    check_forbidden_top_dirs,
    check_no_executable_python_outside_packages,
    check_no_direct_bash_invocations,
    check_no_direct_python_invocations,
    check_no_adhoc_python,
    check_no_ops_generated_placeholder,
    check_no_xtask_refs,
    check_ops_examples_immutable,
    check_ops_generated_tracked,
    check_script_help,
    check_script_ownership,
    check_tracked_timestamp_paths,
)
from ..base import CheckDef
from .enforcement.legacy_guard import check_legacy_package_absent
from .enforcement.module_size import check_module_size
from ...policies.culprits import (
    check_budget_drift_approval,
    check_critical_dir_count_trend,
    check_budget_exceptions_documented,
    check_budget_exceptions_sorted,
    check_budget_metric,
)
from .enforcement.cwd_usage import check_no_path_cwd_usage
from .contracts.command_contracts import (
    check_command_alias_budget,
    check_command_help_docs_drift,
    check_command_metadata_contract,
    check_command_ownership_docs,
    check_internal_commands_not_public,
    check_no_duplicate_command_names,
)
from .enforcement.argparse_policy import check_argparse_policy
from .enforcement.package_shape import (
    check_layout_domain_readmes,
    check_layout_no_legacy_imports,
    check_no_nested_same_name_packages,
)
from .enforcement.package_hygiene import (
    check_folder_intent_contract,
    check_no_empty_packages,
    check_no_placeholder_module_names,
    check_package_has_module_or_readme,
)
from .enforcement.shell_policy import (
    check_no_layout_shadow_configs,
    check_shell_docs_present,
    check_shell_no_network_download_tools,
    check_shell_headers_and_strict_mode,
    check_shell_invocation_via_core_exec,
    check_shell_location_policy,
    check_shell_no_python_direct_calls,
    check_shell_script_budget,
    check_shell_scripts_readonly,
)
from .domains.scripts_dir import check_scripts_dir_absent
from .contracts.public_api import check_public_api_exports
from .contracts.type_coverage import check_type_coverage
from .contracts.dependencies import check_dependency_declarations
from .reachability import check_no_legacy_importers, check_repo_check_modules_registered
from .enforcement.refgrade_proof import check_refgrade_target_shape
from .enforcement.import_policy import (
    check_command_import_lint,
    check_checks_import_lint,
    check_contract_import_boundaries,
    check_cold_import_budget,
    check_compileall_gate,
    check_forbidden_core_integration_dir,
    check_forbidden_deprecated_namespace_dirs,
    check_forbidden_deprecated_namespaces,
    check_import_smoke,
    check_internal_import_boundaries,
    check_no_legacy_obs_imports_in_modern,
    check_no_modern_imports_from_legacy,
    check_runcontext_single_builder,
)
from .enforcement.boundaries.effect_boundaries import (
    check_effect_boundary_exceptions_policy,
    check_forbidden_effect_calls,
    check_subprocess_boundary,
)
from .contracts.pyproject_contracts import (
    check_dependency_gate_targets,
    check_deps_workflow_doc,
    check_deps_command_surface,
    check_dependency_owner_justification,
    check_console_script_entry,
    check_env_docs_present,
    check_optional_dependency_groups,
    check_pyproject_minimalism,
    check_pyproject_no_duplicate_tool_config,
    check_pyproject_required_blocks,
    check_python_module_help,
    check_requirements_artifact_policy,
    check_requirements_sync_with_pyproject,
)
from .contracts.suite_inventory import check_suite_inventory_policy
from .contracts.test_guardrails import (
    check_check_test_coverage,
    check_command_test_coverage,
    check_json_goldens_validate_schema,
    check_suite_marker_rules,
    check_test_duplicate_expectations,
    check_test_ownership_tags,
)
from ..layout.root import (
    FORBIDDEN_ROOT_FILES_CHECK_ID,
    FORBIDDEN_ROOT_FILES_DESCRIPTION,
    FORBIDDEN_ROOT_NAMES_CHECK_ID,
    FORBIDDEN_ROOT_NAMES_DESCRIPTION,
    FORBIDDEN_PATHS_DESCRIPTION,
    FORBIDDEN_PATHS_CHECK_ID,
    ROOT_DETERMINISM_DESCRIPTION,
    ROOT_DETERMINISM_CHECK_ID,
    ROOT_SHAPE_DESCRIPTION,
    ROOT_SHAPE_CHECK_ID,
    DIRECT_SCRIPT_RUNS_DESCRIPTION,
    DIRECT_SCRIPT_RUNS_CHECK_ID,
    run_forbidden_root_files,
    run_forbidden_root_names,
    run_forbidden_paths,
    run_no_direct_script_runs,
    run_root_determinism,
    run_root_shape,
)

CHECKS: tuple[CheckDef, ...] = (
    CheckDef("repo.forbidden_top_dirs", "repo", "forbid top-level forbidden directories", 500, check_forbidden_top_dirs, fix_hint="Remove forbidden root directories."),
    CheckDef("repo.docs_no_ops_generated_refs", "repo", "disallow docs refs to ops generated runtime paths", 800, check_docs_no_ops_generated_run_paths, fix_hint="Replace generated runtime paths with canonical docs references."),
    CheckDef("repo.no_xtask_refs", "repo", "forbid xtask references", 1000, check_no_xtask_refs, fix_hint="Remove xtask references and use atlasctl workflows."),
    CheckDef("repo.no_exec_python_outside_packages", "repo", "forbid executable python outside package boundaries", 1500, check_no_executable_python_outside_packages, fix_hint="Move script into package module or remove executable bit."),
    CheckDef("repo.no_direct_python_invocations", "repo", "forbid direct python script calls in docs/makefiles", 1000, check_no_direct_python_invocations, fix_hint="Use atlasctl command entrypoints instead of python path/to/script.py."),
    CheckDef("repo.no_direct_bash_invocations", "repo", "forbid direct bash script calls in docs/makefiles", 1000, check_no_direct_bash_invocations, fix_hint="Use atlasctl commands instead of bash scripts/... invocations."),
    CheckDef("repo.no_adhoc_python", "repo", "forbid ad-hoc python files outside package boundaries", 1200, check_no_adhoc_python, fix_hint="Migrate ad-hoc python files into package modules."),
    CheckDef("repo.no_tracked_ops_generated", "repo", "ensure ops/_generated has no tracked files", 1000, check_ops_generated_tracked, fix_hint="Untrack generated files and add to ignore policy."),
    CheckDef("repo.no_ops_generated_placeholder", "repo", "forbid placeholder generated dirs", 400, check_no_ops_generated_placeholder, fix_hint="Remove placeholder generated files/directories."),
    CheckDef("repo.ops_examples_immutable", "repo", "enforce immutability of ops examples", 800, check_ops_examples_immutable, fix_hint="Restore example fixtures to committed canonical content."),
    CheckDef("repo.no_tracked_timestamp_paths", "repo", "forbid timestamp-like tracked paths", 1000, check_tracked_timestamp_paths, fix_hint="Remove timestamped tracked files/dirs."),
    CheckDef("repo.duplicate_script_names", "repo", "forbid duplicate script stem names", 1200, check_duplicate_script_names, fix_hint="Rename colliding script names."),
    CheckDef("repo.script_help_coverage", "repo", "validate script help contract coverage", 1500, check_script_help, fix_hint="Add --help contract output to required scripts."),
    CheckDef("repo.script_ownership_coverage", "repo", "validate script ownership coverage", 1500, check_script_ownership, fix_hint="Update ownership metadata for uncovered scripts."),
    CheckDef("repo.no_scripts_dir", "repo", "forbid legacy root scripts dir", 250, check_scripts_dir_absent, fix_hint="Migrate scripts into atlasctl package commands."),
    CheckDef("repo.legacy_package_absent", "repo", "require atlasctl legacy package to be absent", 250, check_legacy_package_absent, fix_hint="Delete packages/atlasctl/src/atlasctl/legacy and migrate importers."),
    CheckDef("repo.module_size", "repo", "enforce module size budget", 400, check_module_size, fix_hint="Split oversized modules into focused submodules."),
    CheckDef(
        "repo.dir_budget_modules",
        "repo",
        "enforce per-directory python module count budget",
        400,
        lambda repo_root: check_budget_metric(repo_root, "modules-per-dir"),
        fix_hint="Split high-density directories into intent-focused subpackages.",
    ),
    CheckDef(
        "repo.dir_budget_py_files",
        "repo",
        "enforce per-directory python file count budget",
        400,
        lambda repo_root: check_budget_metric(repo_root, "py-files-per-dir"),
        fix_hint="Split high-density directories and keep directory fan-in bounded.",
    ),
    CheckDef(
        "repo.dir_budget_loc",
        "repo",
        "enforce per-directory total LOC budget",
        400,
        lambda repo_root: check_budget_metric(repo_root, "dir-loc"),
        fix_hint="Move unrelated files into domain subpackages to reduce dir-level LOC density.",
    ),
    CheckDef(
        "repo.dir_budget_exceptions_documented",
        "repo",
        "ensure budget exceptions are documented",
        300,
        check_budget_exceptions_documented,
        fix_hint="Document each budget exception path in packages/atlasctl/docs/architecture.md.",
    ),
    CheckDef(
        "repo.dir_budget_exceptions_sorted",
        "repo",
        "ensure budget exceptions are sorted deterministically",
        300,
        check_budget_exceptions_sorted,
        fix_hint="Sort [[tool.atlasctl.budgets.exceptions]] entries by path in pyproject.toml.",
    ),
    CheckDef(
        "repo.budget_drift_approval",
        "repo",
        "forbid budget loosening without explicit approval marker",
        300,
        check_budget_drift_approval,
        fix_hint="Update configs/policy/atlasctl-budgets-baseline.json or add approved budget-loosening marker.",
    ),
    CheckDef(
        "repo.dir_count_trend_gate",
        "repo",
        "forbid critical directory file/module count drift above baseline",
        300,
        check_critical_dir_count_trend,
        fix_hint="Split critical directories or update configs/policy/atlasctl-dir-count-baseline.json with approval.",
    ),
    CheckDef(
        "repo.dir_budget_shell_files",
        "repo",
        "enforce per-directory shell file count budget",
        400,
        lambda repo_root: check_budget_metric(repo_root, "shell-files-per-dir"),
        fix_hint="Move shell scripts into approved layout/ops directories and split crowded directories.",
    ),
    CheckDef(
        "repo.file_import_budget",
        "repo",
        "enforce python import count budget per file",
        400,
        lambda repo_root: check_budget_metric(repo_root, "imports-per-file"),
        fix_hint="Reduce import fan-in and use lazy imports where needed.",
    ),
    CheckDef(
        "repo.file_public_symbol_budget",
        "repo",
        "enforce public symbol budget per module",
        400,
        lambda repo_root: check_budget_metric(repo_root, "public-symbols-per-file"),
        fix_hint="Split dumping-ground modules and narrow __all__ exports.",
    ),
    CheckDef(
        "repo.file_complexity_budget",
        "repo",
        "enforce complexity heuristic budget in core/cli",
        400,
        lambda repo_root: check_budget_metric(repo_root, "complexity-heuristic"),
        fix_hint="Split high-complexity control flow and extract focused helpers.",
    ),
    CheckDef(
        "repo.shell_location_policy",
        "repo",
        "forbid shell scripts outside approved directories",
        300,
        check_shell_location_policy,
        fix_hint="Keep shell scripts under checks/layout or ops only.",
    ),
    CheckDef(
        "repo.shell_strict_mode",
        "repo",
        "require shell header and strict mode",
        300,
        check_shell_headers_and_strict_mode,
        fix_hint="Add #!/usr/bin/env bash and set -euo pipefail to all shell scripts.",
    ),
    CheckDef(
        "repo.shell_no_direct_python",
        "repo",
        "forbid direct python invocation in shell scripts",
        300,
        check_shell_no_python_direct_calls,
        fix_hint="Call atlasctl entrypoints instead of python commands in shell scripts.",
    ),
    CheckDef(
        "repo.shell_no_network_fetch",
        "repo",
        "forbid direct curl/wget usage in shell scripts",
        300,
        check_shell_no_network_download_tools,
        fix_hint="Use atlasctl-managed fetch entrypoints or explicit allow annotation.",
    ),
    CheckDef(
        "repo.shell_readonly_checks",
        "repo",
        "forbid direct file writes in layout shell checks",
        300,
        check_shell_scripts_readonly,
        fix_hint="Keep layout shell checks read-only and route outputs through stdout/stderr only.",
    ),
    CheckDef(
        "repo.shell_invocation_boundary",
        "repo",
        "forbid direct shell subprocess invocations outside core.exec",
        300,
        check_shell_invocation_via_core_exec,
        fix_hint="Route shell invocations through core.exec wrapper helpers.",
    ),
    CheckDef(
        "repo.shell_script_budget",
        "repo",
        "cap total shell script count in repository",
        300,
        check_shell_script_budget,
        fix_hint="Port shell scripts to Python modules and delete duplicates.",
    ),
    CheckDef(
        "repo.shell_docs_present",
        "repo",
        "require shell directory README and policy docs",
        300,
        check_shell_docs_present,
        fix_hint="Add README.md and POLICY.md under checks/layout/shell.",
    ),
    CheckDef(
        "repo.layout_no_shadow",
        "repo",
        "enforce no-shadow config policy",
        300,
        check_no_layout_shadow_configs,
        fix_hint="Resolve shadow config sources reported by atlasctl/layout/no_shadow.py.",
    ),
    CheckDef("repo.layout_domain_readmes", "repo", "ensure each layout check domain includes a README", 300, check_layout_domain_readmes, fix_hint="Add README.md to each checks/layout/<domain>/ directory."),
    CheckDef("repo.layout_no_legacy_imports", "repo", "forbid legacy imports in checks/layout modules", 300, check_layout_no_legacy_imports, fix_hint="Remove atlasctl.legacy imports from layout checks."),
    CheckDef(ROOT_SHAPE_CHECK_ID, "repo", ROOT_SHAPE_DESCRIPTION, 500, run_root_shape, fix_hint="Align root entries with checks/layout/root_whitelist.json."),
    CheckDef(FORBIDDEN_ROOT_FILES_CHECK_ID, "repo", FORBIDDEN_ROOT_FILES_DESCRIPTION, 400, run_forbidden_root_files, fix_hint="Remove forbidden junk files from repository root."),
    CheckDef(FORBIDDEN_ROOT_NAMES_CHECK_ID, "repo", FORBIDDEN_ROOT_NAMES_DESCRIPTION, 400, run_forbidden_root_names, fix_hint="Remove forbidden top-level legacy names from repository root."),
    CheckDef(FORBIDDEN_PATHS_CHECK_ID, "repo", FORBIDDEN_PATHS_DESCRIPTION, 500, run_forbidden_paths, fix_hint="Remove forbidden legacy path references from make/docs/workflows."),
    CheckDef(DIRECT_SCRIPT_RUNS_CHECK_ID, "repo", DIRECT_SCRIPT_RUNS_DESCRIPTION, 500, run_no_direct_script_runs, fix_hint="Invoke workflows through make targets instead of direct scripts/ops paths."),
    CheckDef(ROOT_DETERMINISM_CHECK_ID, "repo", ROOT_DETERMINISM_DESCRIPTION, 1500, run_root_determinism, fix_hint="Stabilize generated root outputs so consecutive runs are identical.", slow=True),
    CheckDef(
        "repo.no_nested_same_name_packages",
        "repo",
        "forbid nested package segments with same name",
        300,
        check_no_nested_same_name_packages,
        fix_hint="Flatten nested same-name package segments (example: checks/checks).",
    ),
    CheckDef("repo.no_empty_packages", "repo", "forbid empty non-legacy packages without README", 300, check_no_empty_packages, fix_hint="Add a real module or README.md to package directories."),
    CheckDef(
        "repo.folder_intent_contract",
        "repo",
        "require intent marker for checks directories",
        300,
        check_folder_intent_contract,
        fix_hint="Add README.md or check_*.py module in each checks directory.",
    ),
    CheckDef("repo.no_placeholder_module_names", "repo", "forbid placeholder-like module filenames in modern code", 300, check_no_placeholder_module_names, fix_hint="Rename modules to intent-revealing names."),
    CheckDef("repo.package_has_module_or_readme", "repo", "require each non-legacy package to contain a module or README", 300, check_package_has_module_or_readme, fix_hint="Add module implementation or README.md to document empty package."),
    CheckDef("repo.no_path_cwd_usage", "repo", "forbid Path.cwd usage outside core/repo_root.py", 400, check_no_path_cwd_usage, fix_hint="Use ctx.repo_root or core.repo_root helpers."),
    CheckDef("repo.command_metadata_contract", "repo", "ensure command metadata includes touches/tools/effect declarations", 400, check_command_metadata_contract, fix_hint="Add touches/tools/effect metadata in cli registry."),
    CheckDef("repo.argparse_policy", "repo", "restrict direct argparse parser construction to canonical parser modules", 300, check_argparse_policy, fix_hint="Move parser construction into cli/parser.py or commands/*/parser.py."),
    CheckDef("repo.no_duplicate_command_names", "repo", "ensure command names are unique", 300, check_no_duplicate_command_names, fix_hint="Rename duplicate command/alias entries."),
    CheckDef("repo.command_alias_budget", "repo", "enforce command alias/name budget", 300, check_command_alias_budget, fix_hint="Remove duplicate alias identifiers from command surface."),
    CheckDef("repo.internal_commands_not_public", "repo", "ensure unstable/internal commands are not exposed in public docs", 300, check_internal_commands_not_public, fix_hint="Mark internal commands stable=false and exclude them from public docs."),
    CheckDef("repo.command_ownership_docs", "repo", "ensure command owners are documented", 300, check_command_ownership_docs, fix_hint="Document all command owners in packages/atlasctl/docs/ownership.md."),
    CheckDef("repo.command_help_docs_drift", "repo", "check command help/docs drift", 500, check_command_help_docs_drift, fix_hint="Regenerate docs/_generated/cli.md from current CLI surface."),
    CheckDef("repo.public_api_exports", "repo", "enforce docs/public-api.md coverage for __all__ exports", 300, check_public_api_exports, fix_hint="Document exported symbols in docs/public-api.md or remove them from __all__."),
    CheckDef("repo.type_coverage", "repo", "enforce minimum type coverage in core/contracts", 600, check_type_coverage, fix_hint="Add function annotations in core/contracts until the threshold is met."),
    CheckDef("repo.dependency_declarations", "repo", "ensure pyproject dependency declarations match imports", 600, check_dependency_declarations, fix_hint="Add missing dependencies or remove unused declarations."),
    CheckDef("repo.check_module_reachability", "repo", "ensure repo check modules are imported and reachable via registry", 300, check_repo_check_modules_registered, fix_hint="Import new repo check modules in checks/repo/__init__.py."),
    CheckDef("repo.legacy_zero_importers", "repo", "require zero importers of removed atlasctl legacy namespace", 300, check_no_legacy_importers, fix_hint="Remove imports/references to atlasctl.legacy."),
    CheckDef("repo.pyproject_required_blocks", "repo", "ensure pyproject contains required project and tool config blocks", 300, check_pyproject_required_blocks, fix_hint="Add required [project]/[tool.*] blocks to packages/atlasctl/pyproject.toml."),
    CheckDef("repo.pyproject_no_duplicate_tool_config", "repo", "forbid duplicate tool config files beside pyproject", 300, check_pyproject_no_duplicate_tool_config, fix_hint="Remove duplicated tool config files and keep pyproject as SSOT."),
    CheckDef("repo.console_script_entry", "repo", "ensure atlasctl console script entry exists and points to callable target", 300, check_console_script_entry, fix_hint="Set [project.scripts] atlasctl = \"atlasctl.cli.main:main\" and ensure target is importable."),
    CheckDef("repo.python_module_help", "repo", "ensure python -m atlasctl --help works", 300, check_python_module_help, fix_hint="Ensure atlasctl package entrypoint remains runnable with python -m atlasctl."),
    CheckDef("repo.optional_dependency_groups", "repo", "ensure required pyproject optional-dependency groups exist", 300, check_optional_dependency_groups, fix_hint="Add required [project.optional-dependencies] groups: dev/test/ops/docs."),
    CheckDef("repo.pyproject_minimalism", "repo", "forbid dead/unknown pyproject tool keys", 300, check_pyproject_minimalism, fix_hint="Remove unknown [tool.*] sections or document and allow them explicitly."),
    CheckDef("repo.deps_workflow_doc", "repo", "ensure docs/deps.md matches chosen dependency workflow", 300, check_deps_workflow_doc, fix_hint="Update docs/deps.md and keep requirements.in/requirements.lock.txt in sync."),
    CheckDef("repo.env_docs_present", "repo", "ensure docs/env.md exists and lists canonical env vars", 300, check_env_docs_present, fix_hint="Create docs/env.md and document canonical runtime environment variables."),
    CheckDef("repo.requirements_artifact_policy", "repo", "ensure only route-B requirements artifacts exist", 300, check_requirements_artifact_policy, fix_hint="Keep only requirements.in and requirements.lock.txt in package root for route-B workflow."),
    CheckDef("repo.requirements_sync", "repo", "ensure requirements files match pyproject dev dependency declarations", 300, check_requirements_sync_with_pyproject, fix_hint="Regenerate requirements.lock.txt from requirements.in and keep pyproject optional-deps dev aligned."),
    CheckDef("repo.dependency_owner_justification", "repo", "ensure each dependency has owner and justification", 300, check_dependency_owner_justification, fix_hint="Add dependency ownership + justification entries in docs/deps.md."),
    CheckDef("repo.dependency_gate_targets", "repo", "ensure dependency gate make targets exist", 300, check_dependency_gate_targets, fix_hint="Define deps-lock/deps-sync/deps-check-venv/deps-cold-start in makefiles/scripts.mk."),
    CheckDef("repo.deps_command_surface", "repo", "ensure atlasctl deps command surface is runnable", 300, check_deps_command_surface, fix_hint="Wire atlasctl deps parser/runner and keep command import path valid."),
    CheckDef("repo.tests_no_duplicate_expectations", "repo", "forbid duplicate test function names across test modules", 300, check_test_duplicate_expectations, fix_hint="Rename duplicated test_* functions to avoid conflicting expectations."),
    CheckDef("repo.test_ownership_tags", "repo", "ensure tests declare ownership tags or live in domain directories", 300, check_test_ownership_tags, fix_hint="Add '# test-domain: <domain>' header to top-level tests."),
    CheckDef("repo.suite_marker_rules", "repo", "enforce check-suite-coverage marker file policy", 300, check_suite_marker_rules, fix_hint="Keep check-suite-coverage.markers.txt sorted, unique, and only registered check ids."),
    CheckDef("repo.command_test_coverage", "repo", "ensure each command has explicit test coverage marker", 300, check_command_test_coverage, fix_hint="Add at least one test mentioning each command."),
    CheckDef("repo.json_goldens_validate_schema", "repo", "require schema validation in JSON golden tests", 300, check_json_goldens_validate_schema, fix_hint="Call contracts.validate() before asserting JSON golden snapshots."),
    CheckDef("repo.check_test_coverage", "repo", "ensure each registered check has test or golden coverage marker", 300, check_check_test_coverage, fix_hint="Add test/golden references for uncovered checks."),
    CheckDef(
        "repo.suite_inventory_policy",
        "repo",
        "validate suite inventory coverage and refgrade-required tag policy",
        300,
        check_suite_inventory_policy,
        fix_hint="Assign checks to suites and ensure refgrade complete suites include all refgrade_required checks.",
    ),
    CheckDef("repo.refgrade_target_shape", "repo", "enforce package root minimalism and src no-symlink target shape", 300, check_refgrade_target_shape, fix_hint="Keep package-root items minimal and remove symlinks from src tree."),
    CheckDef("repo.internal_import_boundaries", "repo", "forbid atlasctl.internal imports outside internal namespace", 300, check_internal_import_boundaries, fix_hint="Route shared helpers through public modules instead of atlasctl.internal."),
    CheckDef("repo.modern_no_legacy_imports", "repo", "forbid modern modules from importing atlasctl.legacy", 300, check_no_modern_imports_from_legacy, fix_hint="Migrate callers to canonical modules under atlasctl.core/commands/checks."),
    CheckDef("repo.modern_no_legacy_obs_imports", "repo", "forbid modern modules from importing atlasctl.legacy.obs", 300, check_no_legacy_obs_imports_in_modern, fix_hint="Migrate observability imports to atlasctl.observability."),
    CheckDef("repo.no_deprecated_namespaces", "repo", "forbid imports from atlasctl.check/report/obs namespaces", 300, check_forbidden_deprecated_namespaces, fix_hint="Use atlasctl.checks and atlasctl.reporting canonical namespaces."),
    CheckDef("repo.no_deprecated_namespace_dirs", "repo", "forbid deprecated atlasctl/check report obs directories", 300, check_forbidden_deprecated_namespace_dirs, fix_hint="Remove deprecated namespace directories and keep checks/reporting/observability as canonical roots."),
    CheckDef("repo.no_core_integration_dir", "repo", "forbid deprecated core/integration namespace", 300, check_forbidden_core_integration_dir, fix_hint="Use top-level atlasctl.adapters for integration concerns."),
    CheckDef("repo.contract_import_boundaries", "repo", "enforce contracts/core-contracts import boundaries", 300, check_contract_import_boundaries, fix_hint="Commands/checks should import schema contracts from atlasctl.contracts only."),
    CheckDef("repo.runcontext_single_builder", "repo", "ensure RunContext is built only in core/context.py", 300, check_runcontext_single_builder, fix_hint="Use RunContext.from_args and avoid constructing context-like objects elsewhere."),
    CheckDef("repo.command_import_lint", "repo", "enforce command module import boundaries", 300, check_command_import_lint, fix_hint="Restrict command imports to core/contracts/checks/adapters/commands/cli."),
    CheckDef("repo.checks_import_lint", "repo", "enforce checks module import boundaries", 300, check_checks_import_lint, fix_hint="Restrict checks imports to core/contracts/reporting/adapters/checks."),
    CheckDef("repo.effect_boundaries", "repo", "forbid direct subprocess/fs/env/network effects outside core boundaries", 300, check_forbidden_effect_calls, fix_hint="Route effects through core.exec/core.process/core.fs/core.env/core.network."),
    CheckDef("repo.subprocess_boundary", "repo", "restrict subprocess imports to core execution boundary", 300, check_subprocess_boundary, fix_hint="Use core.exec/core.process for subprocess calls."),
    CheckDef("repo.effect_boundary_exceptions_policy", "repo", "enforce explicit sorted effect boundary exceptions with reasons", 300, check_effect_boundary_exceptions_policy, fix_hint="Keep configs/policy/effect-boundary-exceptions.json sorted and justified."),
    CheckDef("repo.compileall_gate", "repo", "ensure atlasctl source compiles with compileall", 300, check_compileall_gate, fix_hint="Fix syntax/import issues until python -m compileall passes."),
    CheckDef("repo.import_smoke", "repo", "ensure atlasctl package imports in minimal environment", 300, check_import_smoke, fix_hint="Keep top-level imports light and dependency-safe."),
    CheckDef("repo.cold_import_budget", "repo", "enforce cold import time budget for atlasctl package", 300, check_cold_import_budget, fix_hint="Reduce top-level imports and defer heavy initialization."),
)
