apiVersion: apps/v1
kind: Deployment
metadata:
  name: toxiproxy
  namespace: atlas-e2e
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toxiproxy
  template:
    metadata:
      labels:
        app: toxiproxy
    spec:
      containers:
        - name: toxiproxy
          image: ghcr.io/shopify/toxiproxy:2.12.0
          args: ["-host", "0.0.0.0"]
          ports:
            - name: api
              containerPort: 8474
            - name: minio
              containerPort: 19000
---
apiVersion: v1
kind: Service
metadata:
  name: toxiproxy
  namespace: atlas-e2e
spec:
  selector:
    app: toxiproxy
  ports:
    - name: api
      port: 8474
      targetPort: api
    - name: minio
      port: 19000
      targetPort: minio
