fn docs_reference_generate_or_check(
    repo_root: &std::path::Path,
    allow_write: bool,
) -> Result<(Vec<String>, Vec<String>), String> {
    let ref_dir = repo_root.join("artifacts/docs/generated/reference");
    let mut changed = Vec::<String>::new();
    let mut generated = Vec::<String>::new();
    let targets = docs_reference_target_contents(repo_root)?;
    for (rel, content) in targets {
        let path = repo_root.join(rel);
        generated.push(rel.to_string());
        let existing = match std::fs::read_to_string(&path) {
            Ok(value) => value,
            Err(err) if allow_write && err.kind() == std::io::ErrorKind::NotFound => String::new(),
            Err(err) => return Err(format!("read {} failed: {err}", path.display())),
        };
        if existing != content {
            changed.push(rel.to_string());
            if allow_write {
                if let Some(parent) = path.parent() {
                    std::fs::create_dir_all(parent)
                        .map_err(|e| format!("create {} failed: {e}", parent.display()))?;
                }
                std::fs::write(&path, content)
                    .map_err(|e| format!("write {} failed: {e}", path.display()))?;
            }
        }
    }
    let _ = ref_dir;
    Ok((changed, generated))
}

fn docs_reference_target_contents(
    repo_root: &std::path::Path,
) -> Result<Vec<(&'static str, String)>, String> {
    Ok(vec![
        (
            "artifacts/docs/generated/operations-reference/commands.md",
            render_docs_reference_commands(repo_root)?,
        ),
        (
            "artifacts/docs/generated/reference/commands.md",
            render_docs_reference_commands_registry(repo_root)?,
        ),
        (
            "artifacts/docs/generated/reference/schemas.md",
            render_docs_reference_schemas(repo_root)?,
        ),
        (
            "artifacts/docs/generated/reference/configs.md",
            render_docs_reference_configs(repo_root)?,
        ),
        (
            "artifacts/docs/generated/reference/makes-targets.md",
            render_docs_reference_make_targets(repo_root)?,
        ),
        (
            "artifacts/docs/generated/reference/repo-map.md",
            render_docs_reference_repo_map(repo_root)?,
        ),
        (
            "artifacts/docs/generated/operations-reference/ops-surface.md",
            render_docs_reference_ops_surface(repo_root)?,
        ),
        (
            "artifacts/docs/generated/operations-reference/tools.md",
            render_docs_reference_tools(repo_root)?,
        ),
        (
            "artifacts/docs/generated/operations-reference/toolchain.md",
            render_docs_reference_toolchain(repo_root)?,
        ),
        (
            "artifacts/docs/generated/operations-reference/pins.md",
            render_docs_reference_pins(repo_root)?,
        ),
        (
            "artifacts/docs/generated/operations-reference/gates.md",
            render_docs_reference_gates(repo_root)?,
        ),
        (
            "artifacts/docs/generated/operations-reference/drills.md",
            render_docs_reference_drills(repo_root)?,
        ),
        (
            "artifacts/docs/generated/operations-reference/schema-index.md",
            render_docs_reference_schema_index(),
        ),
        (
            "artifacts/docs/generated/operations-reference/evidence-model.md",
            render_docs_reference_evidence_model(repo_root)?,
        ),
        (
            "artifacts/docs/generated/operations-reference/what-breaks-if-removed.md",
            render_docs_reference_what_breaks(repo_root)?,
        ),
    ])
}

fn wrap_generated_reference_page(title: &str, audience: &str, owner: &str, body: String) -> String {
    format!(
        "---\n\
title: {title}\n\
audience: {audience}\n\
type: reference\n\
status: generated\n\
owner: {owner}\n\
last_reviewed: 2026-03-16\n\
---\n\n\
This page is generated by `bijux dev atlas docs reference generate --allow-subprocess --allow-write`.\n\n\
{body}"
    )
}

fn render_docs_reference_commands_registry(repo_root: &std::path::Path) -> Result<String, String> {
    let value: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(repo_root.join("configs/generated/docs/command-index.json"))
            .map_err(|e| format!("read command-index.json failed: {e}"))?,
    )
    .map_err(|e| format!("parse command-index.json failed: {e}"))?;
    let mut rows = value["commands"]
        .as_array()
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .map(|row| {
            (
                row["id"].as_str().unwrap_or_default().to_string(),
                row["kind"].as_str().unwrap_or_default().to_string(),
                row["purpose"].as_str().unwrap_or_default().to_string(),
            )
        })
        .collect::<Vec<_>>();
    rows.sort();

    let mut out = String::new();
    out.push_str("# Commands Reference\n\n");
    out.push_str("- Owner: `bijux-atlas-operations`\n");
    out.push_str("- Tier: `generated`\n");
    out.push_str("- Audience: `operators`\n");
    out.push_str("- Stability: `stable`\n");
    out.push_str("- Source-of-truth: `configs/generated/docs/command-index.json`\n\n");
    out.push_str("## Purpose\n\n");
    out.push_str(
        "Generated reference for the maintainer command registry. Narrative docs should describe intent and link here for the complete surface.\n\n",
    );
    out.push_str("## Commands\n\n| Command ID | Kind | Purpose |\n| --- | --- | --- |\n");
    for (id, kind, purpose) in rows {
        out.push_str(&format!("| `{id}` | `{kind}` | {purpose} |\n"));
    }
    out.push_str("\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n");
    out.push_str("\n## Stability\n\nThis generated page is a checked-in reference surface. Regenerate it when the command inventory changes so docs and automation stay aligned.\n");
    Ok(wrap_generated_reference_page(
        "Commands Reference",
        "operators",
        "bijux-atlas-operations",
        out,
    ))
}

fn render_docs_reference_schemas(repo_root: &std::path::Path) -> Result<String, String> {
    let value: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(repo_root.join("configs/generated/docs/schema-index.json"))
            .map_err(|e| format!("read schema-index.json failed: {e}"))?,
    )
    .map_err(|e| format!("parse schema-index.json failed: {e}"))?;
    let mut rows = value["schemas"]
        .as_array()
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .map(|row| {
            (
                row["path"].as_str().unwrap_or_default().to_string(),
                row["title"].as_str().unwrap_or_default().to_string(),
                row["kind"].as_str().unwrap_or_default().to_string(),
            )
        })
        .collect::<Vec<_>>();
    rows.sort();

    let mut out = String::new();
    out.push_str("# Schemas Reference\n\n");
    out.push_str("- Owner: `bijux-atlas-operations`\n");
    out.push_str("- Tier: `generated`\n");
    out.push_str("- Audience: `operators`\n");
    out.push_str("- Stability: `stable`\n");
    out.push_str("- Source-of-truth: `configs/generated/docs/schema-index.json`\n\n");
    out.push_str("## Purpose\n\nGenerated reference for checked-in schemas and schema-derived docs surfaces.\n\n");
    out.push_str("## Schemas\n\n| Path | Title | Kind |\n| --- | --- | --- |\n");
    for (path, title, kind) in rows {
        out.push_str(&format!("| `{path}` | {title} | `{kind}` |\n"));
    }
    out.push_str("\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n");
    out.push_str("\n## Stability\n\nThis page is generated from the checked-in schema inventory and should change only when the schema set changes.\n");
    Ok(wrap_generated_reference_page(
        "Schemas Reference",
        "operators",
        "bijux-atlas-operations",
        out,
    ))
}

fn render_docs_reference_configs(repo_root: &std::path::Path) -> Result<String, String> {
    let value: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(repo_root.join("configs/registry/inventory/consumers.json"))
            .map_err(|e| format!("read configs inventory failed: {e}"))?,
    )
    .map_err(|e| format!("parse configs inventory failed: {e}"))?;
    let mut rows = value["groups"]
        .as_object()
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .map(|(group, consumers)| {
            let joined = consumers
                .as_array()
                .into_iter()
                .flatten()
                .filter_map(|v| v.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            (group, joined)
        })
        .collect::<Vec<_>>();
    rows.sort_by_key(|(group, _)| group.clone());

    let mut out = String::new();
    out.push_str("# Configs Reference\n\n");
    out.push_str("- Owner: `bijux-atlas-operations`\n");
    out.push_str("- Tier: `generated`\n");
    out.push_str("- Audience: `operators`\n");
    out.push_str("- Stability: `stable`\n");
    out.push_str("- Source-of-truth: `configs/registry/inventory/consumers.json`\n\n");
    out.push_str("## Purpose\n\nGenerated reference for governed config groups and their declared consumers.\n\n");
    out.push_str("## Config Groups\n\n| Group | Consumers |\n| --- | --- |\n");
    for (group, consumers) in rows {
        out.push_str(&format!("| `{group}` | `{consumers}` |\n"));
    }
    out.push_str("\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n");
    out.push_str("\n## Stability\n\nTreat this page as generated evidence for governed config groups and their declared consumers.\n");
    Ok(wrap_generated_reference_page(
        "Configs Reference",
        "operators",
        "bijux-atlas-operations",
        out,
    ))
}

fn render_docs_reference_make_targets(repo_root: &std::path::Path) -> Result<String, String> {
    let value: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(
            repo_root.join("configs/sources/operations/ops/makes-targets.json"),
        )
        .map_err(|e| format!("read make target registry failed: {e}"))?,
    )
    .map_err(|e| format!("parse make target registry failed: {e}"))?;
    let mut rows = value["targets"]
        .as_array()
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .map(|row| {
            (
                row["name"].as_str().unwrap_or_default().to_string(),
                row["surface"].as_str().unwrap_or_default().to_string(),
                row["description"].as_str().unwrap_or_default().to_string(),
            )
        })
        .collect::<Vec<_>>();
    rows.sort();

    let mut out = String::new();
    out.push_str("# Make Targets Reference\n\n");
    out.push_str("- Owner: `bijux-atlas-operations`\n");
    out.push_str("- Tier: `generated`\n");
    out.push_str("- Audience: `operators`\n");
    out.push_str("- Stability: `stable`\n");
    out.push_str("- Source-of-truth: `configs/sources/operations/ops/makes-targets.json`\n\n");
    out.push_str("## Purpose\n\nGenerated reference for governed make wrapper targets and their declared surface intent.\n\n");
    out.push_str("## Targets\n\n| Target | Surface | Description |\n| --- | --- | --- |\n");
    for (name, surface, description) in rows {
        out.push_str(&format!("| `{name}` | `{surface}` | {description} |\n"));
    }
    out.push_str("\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n");
    out.push_str("\n## Stability\n\nThis page is generated from the governed make target inventory and should remain synchronized with the checked-in registry.\n");
    Ok(wrap_generated_reference_page(
        "Make Targets Reference",
        "operators",
        "bijux-atlas-operations",
        out,
    ))
}

fn render_docs_reference_repo_map(_repo_root: &std::path::Path) -> Result<String, String> {
    Ok(wrap_generated_reference_page(
        "Repository Map",
        "operators",
        "bijux-atlas-operations",
        "# Repository Map\n\n\
- Owner: `bijux-atlas-operations`\n\
- Type: `reference`\n\
- Audience: `operator`\n\
- Stability: `stable`\n\
- Source-of-truth: repo layout and checked-in docs entrypoints\n\n\
## Purpose\n\n\
This page is the stable reader entrypoint for repository layout. Use the curated layout guide and section entrypoints to\n\
understand ownership, boundaries, and where material lives.\n\n\
## Canonical Inputs\n\n\
- `docs/05-architecture/source-layout-and-ownership.md`\n\
- `docs/index.md`\n\
- `docs/07-reference/index.md`\n\n\
## Reader Guidance\n\n\
Start with the curated layout guide when you need to understand ownership or subsystem boundaries. Follow the nearest\n\
checked-in index page in the area you are working in rather than relying on generated inventory artifacts.\n\n\
## Stability\n\n\
This page is a generated navigation aid and should remain aligned with the current repository layout.\n"
        .to_string(),
    ))
}

fn run_bijux_dev_atlas_help(repo_root: &std::path::Path, args: &[&str]) -> Result<String, String> {
    let output = std::process::Command::new("cargo")
        .current_dir(repo_root)
        .args(["run", "-q", "-p", "bijux-dev-atlas", "--"])
        .args(args)
        .output()
        .map_err(|e| format!("spawn cargo for docs reference help failed: {e}"))?;
    if !output.status.success() {
        return Err(format!(
            "cargo help command failed ({}): {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        ));
    }
    Ok(String::from_utf8(output.stdout)
        .map_err(|e| format!("invalid utf8 in help output: {e}"))?
        .trim_end()
        .to_string())
}

fn trim_help_usage_and_commands(help: &str) -> String {
    let mut out = Vec::new();
    for line in help.lines() {
        if line.starts_with("Options:") {
            break;
        }
        out.push(line.trim_end());
    }
    while out.last().is_some_and(|line| line.is_empty()) {
        out.pop();
    }
    out.join("\n")
}

fn render_docs_reference_commands(repo_root: &std::path::Path) -> Result<String, String> {
    let root_help =
        trim_help_usage_and_commands(&run_bijux_dev_atlas_help(repo_root, &["--help"])?);
    let ops_help =
        trim_help_usage_and_commands(&run_bijux_dev_atlas_help(repo_root, &["ops", "--help"])?);
    Ok(wrap_generated_reference_page(
        "Command Surface Reference",
        "operators",
        "bijux-atlas-operations",
        format!(
        "# Command Surface Reference\n\n- Owner: `bijux-atlas-operations`\n- Tier: `generated`\n- Audience: `operators`\n- Stability: `stable`\n- Source-of-truth: `bijux dev atlas --help`, `bijux dev atlas ops --help`, `configs/sources/operations/ops/makes-targets.json`\n\n## Purpose\n\nGenerated reference for the supported command surface. Narrative docs should link here instead of restating command lists.\n\n## bijux-dev-atlas\n\n```text\n{root_help}\n```\n\n## bijux-dev-atlas ops\n\n```text\n{ops_help}\n```\n\n## Make Wrapper Surface\n\nSee `configs/sources/operations/ops/makes-targets.json` and the generated ops surface artifacts. Narrative docs must not duplicate long `make ops-*` command lists.\n\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n\n## Stability\n\nThis page is generated from the checked-in command surface and should remain aligned with the current control plane.\n"
        ),
    ))
}

fn render_docs_reference_ops_surface(repo_root: &std::path::Path) -> Result<String, String> {
    let value: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(repo_root.join("ops/inventory/surfaces.json"))
            .map_err(|e| format!("read surfaces.json failed: {e}"))?,
    )
    .map_err(|e| format!("parse surfaces.json failed: {e}"))?;
    let mut entrypoints = value["entrypoints"]
        .as_array()
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .filter_map(|v| v.as_str().map(ToString::to_string))
        .collect::<Vec<_>>();
    entrypoints.sort();
    let mut commands = value["bijux-dev-atlas_commands"]
        .as_array()
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .filter_map(|v| v.as_str().map(ToString::to_string))
        .collect::<Vec<_>>();
    commands.sort();
    let mut actions = value["actions"].as_array().cloned().unwrap_or_default();
    actions.sort_by_key(|row| row["id"].as_str().unwrap_or_default().to_string());
    let mut out = String::new();
    out.push_str("# Ops Surface Reference\n\n");
    out.push_str("- Owner: `bijux-atlas-operations`\n- Tier: `generated`\n- Audience: `operators`\n- Stability: `stable`\n- Source-of-truth: `ops/inventory/surfaces.json`, `ops/_generated.example/control-plane-surface-list.json`\n\n");
    out.push_str(
        "## Purpose\n\nGenerated ops surface reference derived from inventory surfaces.\n\n",
    );
    out.push_str("## Entry Points\n\n");
    for item in entrypoints {
        out.push_str(&format!("- `{item}`\n"));
    }
    out.push_str("\n## bijux-dev-atlas Commands\n\n");
    for item in commands {
        out.push_str(&format!("- `{item}`\n"));
    }
    out.push_str("\n## Actions\n\n| Action ID | Domain | Command | Dry Run | Artifacts |\n| --- | --- | --- | --- | --- |\n");
    for item in actions {
        let command = item["command"]
            .as_array()
            .cloned()
            .unwrap_or_default()
            .into_iter()
            .filter_map(|value| value.as_str().map(ToString::to_string))
            .collect::<Vec<_>>()
            .join(" ");
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` | `{}` |\n",
            item["id"].as_str().unwrap_or_default(),
            item["domain"].as_str().unwrap_or_default(),
            command,
            item["dry_run"].as_str().unwrap_or_default(),
            item["artifacts_policy"].as_str().unwrap_or_default()
        ));
    }
    out.push_str("\n## See Also\n\n- `ops/_generated.example/control-plane-surface-list.json` (generated surface evidence)\n- `ops/inventory/surfaces.json` (machine truth)\n\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n");
    out.push_str("\n## Stability\n\nThis page is generated from the ops surface inventory. Change the inventory first, then regenerate the docs snapshot.\n");
    Ok(wrap_generated_reference_page(
        "Ops Surface Reference",
        "operators",
        "bijux-atlas-operations",
        out,
    ))
}

fn render_docs_reference_tools(repo_root: &std::path::Path) -> Result<String, String> {
    let text = std::fs::read_to_string(repo_root.join("ops/inventory/tools.toml"))
        .map_err(|e| format!("read tools.toml failed: {e}"))?;
    let value: toml::Value =
        toml::from_str(&text).map_err(|e| format!("parse tools.toml failed: {e}"))?;
    let mut rows = value["tools"].as_array().cloned().unwrap_or_default();
    rows.sort_by_key(|row| row["name"].as_str().unwrap_or_default().to_string());
    let mut out = String::new();
    out.push_str("# Tools Reference\n\n- Owner: `bijux-atlas-operations`\n- Tier: `generated`\n- Audience: `operators`\n- Stability: `stable`\n- Source-of-truth: `ops/inventory/tools.toml`\n\n## Purpose\n\nGenerated reference for governed external tools and probe contracts.\n\n## Tools\n\n| Tool | Required | Probe Args | Version Regex |\n| --- | --- | --- | --- |\n");
    for row in rows {
        let probe = row["probe_argv"]
            .as_array()
            .into_iter()
            .flatten()
            .filter_map(|v| v.as_str())
            .collect::<Vec<_>>()
            .join(" ");
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | `{}` |\n",
            row["name"].as_str().unwrap_or_default(),
            row["required"].as_bool().unwrap_or(false),
            probe,
            row["version_regex"].as_str().unwrap_or_default()
        ));
    }
    out.push_str("\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n");
    out.push_str("\n## Stability\n\nThis page reflects the checked-in tool inventory and should remain generated rather than edited by hand.\n");
    Ok(wrap_generated_reference_page(
        "Tools Reference",
        "operators",
        "bijux-atlas-operations",
        out,
    ))
}

fn render_docs_reference_toolchain(repo_root: &std::path::Path) -> Result<String, String> {
    let value: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(repo_root.join("ops/inventory/toolchain.json"))
            .map_err(|e| format!("read toolchain.json failed: {e}"))?,
    )
    .map_err(|e| format!("parse toolchain.json failed: {e}"))?;
    let mut out = String::new();
    out.push_str("# Toolchain Reference\n\n- Owner: `bijux-atlas-operations`\n- Tier: `generated`\n- Audience: `operators`\n- Stability: `stable`\n- Source-of-truth: `ops/inventory/toolchain.json`\n\n## Purpose\n\nGenerated reference for the pinned repository toolchain, images, and GitHub Action digests.\n\n## Tools\n\n| Tool | Required | Probe Args |\n| --- | --- | --- |\n");
    let mut tools = value["tools"]
        .as_object()
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .collect::<Vec<_>>();
    tools.sort_by_key(|(k, _)| k.clone());
    for (name, row) in tools {
        let probe = row["probe_argv"]
            .as_array()
            .into_iter()
            .flatten()
            .filter_map(|v| v.as_str())
            .collect::<Vec<_>>()
            .join(" ");
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` |\n",
            name,
            row["required"].as_bool().unwrap_or(false),
            probe
        ));
    }
    out.push_str("\n## Images\n\n| Image Key | Reference |\n| --- | --- |\n");
    let mut images = value["images"]
        .as_object()
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .collect::<Vec<_>>();
    images.sort_by_key(|(k, _)| k.clone());
    for (k, v) in images {
        out.push_str(&format!(
            "| `{}` | `{}` |\n",
            k,
            v.as_str().unwrap_or_default()
        ));
    }
    out.push_str("\n## GitHub Actions Pins\n\n| Action | Ref | SHA |\n| --- | --- | --- |\n");
    let mut actions = value["github_actions"]
        .as_object()
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .collect::<Vec<_>>();
    actions.sort_by_key(|(k, _)| k.clone());
    for (action, row) in actions {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` |\n",
            action,
            row["ref"].as_str().unwrap_or_default(),
            row["sha"].as_str().unwrap_or_default()
        ));
    }
    out.push_str("\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n");
    out.push_str("\n## Stability\n\nThis page is generated from the pinned toolchain inventory. Update the inventory first, then regenerate the docs snapshot.\n");
    Ok(wrap_generated_reference_page(
        "Toolchain Reference",
        "operators",
        "bijux-atlas-operations",
        out,
    ))
}

fn render_docs_reference_pins(repo_root: &std::path::Path) -> Result<String, String> {
    let value: serde_yaml::Value = serde_yaml::from_str(
        &std::fs::read_to_string(repo_root.join("ops/inventory/pins.yaml"))
            .map_err(|e| format!("read pins.yaml failed: {e}"))?,
    )
    .map_err(|e| format!("parse pins.yaml failed: {e}"))?;
    let mut rows = Vec::<(String, String, String)>::new();
    collect_yaml_rows("root", &value, &mut rows);
    rows.sort();
    let mut out = String::new();
    out.push_str("# Pins Reference\n\n- Owner: `bijux-atlas-operations`\n- Tier: `generated`\n- Audience: `operators`\n- Stability: `stable`\n- Source-of-truth: `ops/inventory/pins.yaml`\n\n## Purpose\n\nGenerated reference for the repository pin inventory.\n\n## Pins\n\n| Section | Key | Value |\n| --- | --- | --- |\n");
    for (section, key, val) in rows {
        out.push_str(&format!("| `{}` | `{}` | `{}` |\n", section, key, val));
    }
    out.push_str("\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n");
    out.push_str(
        "\n## Stability\n\nTreat this page as generated evidence of the checked-in pin registry.\n",
    );
    Ok(wrap_generated_reference_page(
        "Pins Reference",
        "operators",
        "bijux-atlas-operations",
        out,
    ))
}

fn collect_yaml_rows(
    prefix: &str,
    value: &serde_yaml::Value,
    out: &mut Vec<(String, String, String)>,
) {
    if let serde_yaml::Value::Mapping(map) = value {
        for (k, v) in map {
            let key = k.as_str().unwrap_or_default();
            if prefix == "root"
                && !matches!(
                    v,
                    serde_yaml::Value::Mapping(_) | serde_yaml::Value::Sequence(_)
                )
            {
                out.push((prefix.to_string(), key.to_string(), yaml_scalar_string(v)));
            } else {
                match v {
                    serde_yaml::Value::Mapping(inner) => {
                        for (ik, iv) in inner {
                            out.push((
                                key.to_string(),
                                ik.as_str().unwrap_or_default().to_string(),
                                yaml_scalar_string(iv),
                            ));
                        }
                    }
                    serde_yaml::Value::Sequence(seq) => {
                        for (idx, item) in seq.iter().enumerate() {
                            out.push((key.to_string(), idx.to_string(), yaml_scalar_string(item)));
                        }
                    }
                    _ => out.push((prefix.to_string(), key.to_string(), yaml_scalar_string(v))),
                }
            }
        }
    }
}

fn yaml_scalar_string(v: &serde_yaml::Value) -> String {
    match v {
        serde_yaml::Value::Null => "null".to_string(),
        serde_yaml::Value::Bool(b) => b.to_string(),
        serde_yaml::Value::Number(n) => n.to_string(),
        serde_yaml::Value::String(s) => s.clone(),
        _ => serde_yaml::to_string(v)
            .unwrap_or_default()
            .trim()
            .to_string(),
    }
}

fn render_docs_reference_gates(repo_root: &std::path::Path) -> Result<String, String> {
    let value: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(repo_root.join("ops/inventory/gates.json"))
            .map_err(|e| format!("read gates.json failed: {e}"))?,
    )
    .map_err(|e| format!("parse gates.json failed: {e}"))?;
    let mut gates = value["gates"].as_array().cloned().unwrap_or_default();
    gates.sort_by_key(|g| g["id"].as_str().unwrap_or_default().to_string());
    let mut out = String::new();
    out.push_str("# Gates Reference\n\n- Owner: `bijux-atlas-operations`\n- Tier: `generated`\n- Audience: `operators`\n- Stability: `stable`\n- Source-of-truth: `ops/inventory/gates.json`\n\n## Purpose\n\nGenerated reference for governed release and validation gates.\n\n## Gates\n\n| Gate ID | Category | Action ID | Description |\n| --- | --- | --- | --- |\n");
    for gate in gates {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} |\n",
            gate["id"].as_str().unwrap_or_default(),
            gate["category"].as_str().unwrap_or_default(),
            gate["action_id"].as_str().unwrap_or_default(),
            gate["description"].as_str().unwrap_or_default()
        ));
    }
    out.push_str("\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n");
    out.push_str("\n## Stability\n\nThis page reflects the checked-in gates inventory and should stay generated from that registry.\n");
    Ok(wrap_generated_reference_page(
        "Gates Reference",
        "operators",
        "bijux-atlas-operations",
        out,
    ))
}

fn render_docs_reference_drills(repo_root: &std::path::Path) -> Result<String, String> {
    let value: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(repo_root.join("ops/inventory/drills.json"))
            .map_err(|e| format!("read drills.json failed: {e}"))?,
    )
    .map_err(|e| format!("parse drills.json failed: {e}"))?;
    let mut drills = value["drills"]
        .as_array()
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .map(|v| {
            v.as_str()
                .map(ToString::to_string)
                .unwrap_or_else(|| v["id"].as_str().unwrap_or_default().to_string())
        })
        .collect::<Vec<_>>();
    drills.sort();
    let mut out = String::new();
    out.push_str("# Drills Reference\n\n- Owner: `bijux-atlas-operations`\n- Tier: `generated`\n- Audience: `operators`\n- Stability: `stable`\n- Source-of-truth: `ops/inventory/drills.json`\n\n## Purpose\n\nGenerated reference for the drill registry used by ops exercises and verification.\n\n## Drills\n\n");
    for drill in drills {
        out.push_str(&format!("- `{drill}`\n"));
    }
    out.push_str("\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n");
    out.push_str("\n## Stability\n\nThis page should mirror the drill inventory exactly and remain generated from that source.\n");
    Ok(wrap_generated_reference_page(
        "Drills Reference",
        "operators",
        "bijux-atlas-operations",
        out,
    ))
}

fn render_docs_reference_schema_index() -> String {
    wrap_generated_reference_page(
        "Schema Index Reference",
        "operators",
        "bijux-atlas-operations",
        "# Schema Index Reference\n\n- Owner: `bijux-atlas-operations`\n- Tier: `generated`\n- Audience: `operators`\n- Stability: `stable`\n- Source-of-truth: `ops/schema/generated/schema-index.json`\n\n## Purpose\n\nThis page points readers to the canonical generated schema index without duplicating that inventory.\n\n## Canonical Source\n\n- `ops/schema/generated/schema-index.json` is the authoritative generated schema index.\n- This page is a docs-site reference pointer to avoid duplicating the schema table.\n\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n\n## Stability\n\nThis page should change only when the schema index source changes.\n"
            .to_string(),
    )
}

fn render_docs_reference_evidence_model(repo_root: &std::path::Path) -> Result<String, String> {
    let levels: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(repo_root.join("ops/schema/report/evidence-levels.schema.json"))
            .map_err(|e| format!("read evidence-levels schema failed: {e}"))?,
    )
    .map_err(|e| format!("parse evidence-levels schema failed: {e}"))?;
    let _bundle: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(
            repo_root.join("ops/schema/report/release-evidence-bundle.schema.json"),
        )
        .map_err(|e| format!("read release-evidence-bundle schema failed: {e}"))?,
    )
    .map_err(|e| format!("parse release-evidence-bundle schema failed: {e}"))?;
    Ok(wrap_generated_reference_page(
        "Evidence Model Reference",
        "operators",
        "bijux-atlas-operations",
        format!(
        "# Evidence Model Reference\n\n- Owner: `bijux-atlas-operations`\n- Tier: `generated`\n- Audience: `operators`\n- Stability: `stable`\n- Source-of-truth: `ops/schema/report/evidence-levels.schema.json`, `ops/schema/report/release-evidence-bundle.schema.json`\n\n## Purpose\n\nGenerated reference for the evidence schemas that define repository release evidence levels and bundle shape.\n\n## Canonical Schemas\n\n- `ops/schema/report/evidence-levels.schema.json`\n- `ops/schema/report/release-evidence-bundle.schema.json`\n\n## Notes\n\n- evidence-levels schema title: `{}`\n",
        levels["title"].as_str().unwrap_or_default()
        ) + "\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n\n## Stability\n\nThis generated page summarizes the checked-in evidence schemas and should remain aligned with them.\n",
    ))
}

fn render_docs_reference_what_breaks(repo_root: &std::path::Path) -> Result<String, String> {
    let value: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(
            repo_root.join("ops/_generated.example/what-breaks-if-removed-report.json"),
        )
        .map_err(|e| format!("read what-breaks-if-removed report failed: {e}"))?,
    )
    .map_err(|e| format!("parse what-breaks-if-removed report failed: {e}"))?;
    let mut out = String::new();
    out.push_str("# What Breaks If Removed Reference\n\n- Owner: `bijux-atlas-operations`\n- Tier: `generated`\n- Audience: `operators`\n- Stability: `stable`\n- Source-of-truth: `ops/_generated.example/what-breaks-if-removed-report.json`\n\n## Purpose\n\nGenerated reference for curated removal-impact evidence.\n\n## Removal Impact Targets\n\n| Path | Impact | Consumers |\n| --- | --- | --- |\n");
    for row in value["targets"].as_array().into_iter().flatten() {
        let consumers = row["consumers"]
            .as_array()
            .into_iter()
            .flatten()
            .filter_map(|v| v.as_str())
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` |\n",
            row["path"].as_str().unwrap_or_default(),
            row["impact"].as_str().unwrap_or_default(),
            consumers
        ));
    }
    out.push_str("\n## Regenerate\n\n- `bijux dev atlas docs reference generate --allow-subprocess --allow-write`\n");
    out.push_str("\n## Stability\n\nThis page should reflect the checked-in removal-impact example report and stay generated from that input.\n");
    Ok(wrap_generated_reference_page(
        "What Breaks If Removed Reference",
        "operators",
        "bijux-atlas-operations",
        out,
    ))
}
