// SPDX-License-Identifier: Apache-2.0
//! Canonical observability metrics registry for control-plane explainability.

use serde::Serialize;

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum MetricCategory {
    Runtime,
    Query,
    Ingest,
    Ops,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum MetricSeverity {
    Low,
    Medium,
    High,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum MetricStability {
    Stable,
    Experimental,
}

#[derive(Debug, Clone, Serialize)]
pub struct MetricMetadata {
    pub id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub unit: &'static str,
    pub category: MetricCategory,
    pub severity: MetricSeverity,
    pub stability: MetricStability,
    pub labels: &'static [&'static str],
    pub cardinality_budget: u32,
    pub version: &'static str,
}

pub fn registry() -> Vec<MetricMetadata> {
    let mut rows = vec![
        MetricMetadata {
            id: "MET-RUNTIME-UPTIME-001",
            name: "atlas_runtime_uptime_seconds",
            description: "Runtime process uptime.",
            unit: "seconds",
            category: MetricCategory::Runtime,
            severity: MetricSeverity::Medium,
            stability: MetricStability::Stable,
            labels: &["subsystem", "version"],
            cardinality_budget: 20,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-RUNTIME-MEMORY-001",
            name: "atlas_runtime_process_memory_bytes",
            description: "Process resident memory usage.",
            unit: "bytes",
            category: MetricCategory::Runtime,
            severity: MetricSeverity::High,
            stability: MetricStability::Stable,
            labels: &["subsystem", "version"],
            cardinality_budget: 20,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-RUNTIME-CPU-001",
            name: "atlas_runtime_process_cpu_percent",
            description: "Process CPU utilization percentage.",
            unit: "percent",
            category: MetricCategory::Runtime,
            severity: MetricSeverity::High,
            stability: MetricStability::Stable,
            labels: &["subsystem", "version"],
            cardinality_budget: 20,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-RUNTIME-THREADS-001",
            name: "atlas_runtime_thread_count",
            description: "Runtime thread count.",
            unit: "count",
            category: MetricCategory::Runtime,
            severity: MetricSeverity::Medium,
            stability: MetricStability::Stable,
            labels: &["subsystem", "version"],
            cardinality_budget: 20,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-RUNTIME-FDS-001",
            name: "atlas_runtime_open_file_descriptors",
            description: "Open file descriptor count.",
            unit: "count",
            category: MetricCategory::Runtime,
            severity: MetricSeverity::Medium,
            stability: MetricStability::Stable,
            labels: &["subsystem", "version"],
            cardinality_budget: 20,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-QUERY-TOTAL-001",
            name: "atlas_query_total",
            description: "Total query requests.",
            unit: "count",
            category: MetricCategory::Query,
            severity: MetricSeverity::High,
            stability: MetricStability::Stable,
            labels: &["route", "status_code", "dataset"],
            cardinality_budget: 200,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-QUERY-LATENCY-001",
            name: "atlas_query_latency_seconds",
            description: "Query latency histogram.",
            unit: "seconds",
            category: MetricCategory::Query,
            severity: MetricSeverity::High,
            stability: MetricStability::Stable,
            labels: &["route", "dataset"],
            cardinality_budget: 150,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-QUERY-ERROR-RATE-001",
            name: "atlas_query_error_rate",
            description: "Query error ratio.",
            unit: "ratio",
            category: MetricCategory::Query,
            severity: MetricSeverity::High,
            stability: MetricStability::Stable,
            labels: &["route", "dataset"],
            cardinality_budget: 150,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-QUERY-CONCURRENCY-001",
            name: "atlas_query_concurrency",
            description: "Concurrent query requests.",
            unit: "count",
            category: MetricCategory::Query,
            severity: MetricSeverity::Medium,
            stability: MetricStability::Stable,
            labels: &["route"],
            cardinality_budget: 60,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-QUERY-CACHE-HIT-001",
            name: "atlas_query_cache_hit_ratio",
            description: "Query cache hit ratio.",
            unit: "ratio",
            category: MetricCategory::Query,
            severity: MetricSeverity::Medium,
            stability: MetricStability::Stable,
            labels: &["cache_layer"],
            cardinality_budget: 40,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-INGEST-THROUGHPUT-001",
            name: "atlas_ingest_throughput_items_per_second",
            description: "Ingest throughput.",
            unit: "items_per_second",
            category: MetricCategory::Ingest,
            severity: MetricSeverity::High,
            stability: MetricStability::Stable,
            labels: &["pipeline", "dataset"],
            cardinality_budget: 120,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-INGEST-ERRORS-001",
            name: "atlas_ingest_errors_total",
            description: "Total ingest failures.",
            unit: "count",
            category: MetricCategory::Ingest,
            severity: MetricSeverity::High,
            stability: MetricStability::Stable,
            labels: &["pipeline", "error_class"],
            cardinality_budget: 120,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-INGEST-QUEUE-DEPTH-001",
            name: "atlas_ingest_queue_depth",
            description: "Ingest queue depth.",
            unit: "count",
            category: MetricCategory::Ingest,
            severity: MetricSeverity::Medium,
            stability: MetricStability::Stable,
            labels: &["pipeline"],
            cardinality_budget: 50,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-INGEST-LATENCY-001",
            name: "atlas_ingest_latency_seconds",
            description: "Ingest processing latency.",
            unit: "seconds",
            category: MetricCategory::Ingest,
            severity: MetricSeverity::Medium,
            stability: MetricStability::Stable,
            labels: &["pipeline", "dataset"],
            cardinality_budget: 120,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-INGEST-ARTIFACT-VALIDATION-001",
            name: "atlas_ingest_artifact_validation_failures_total",
            description: "Artifact validation failures during ingest.",
            unit: "count",
            category: MetricCategory::Ingest,
            severity: MetricSeverity::High,
            stability: MetricStability::Stable,
            labels: &["artifact_type", "validation_rule"],
            cardinality_budget: 80,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-ARTIFACT-LOAD-LATENCY-001",
            name: "atlas_artifact_load_latency_seconds",
            description: "Artifact load latency.",
            unit: "seconds",
            category: MetricCategory::Ops,
            severity: MetricSeverity::Medium,
            stability: MetricStability::Stable,
            labels: &["artifact_type"],
            cardinality_budget: 50,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-ARTIFACT-CACHE-SIZE-001",
            name: "atlas_artifact_cache_size_bytes",
            description: "Artifact cache current size.",
            unit: "bytes",
            category: MetricCategory::Ops,
            severity: MetricSeverity::Medium,
            stability: MetricStability::Stable,
            labels: &["cache_layer"],
            cardinality_budget: 30,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-ARTIFACT-INTEGRITY-FAILURES-001",
            name: "atlas_artifact_integrity_failures_total",
            description: "Artifact integrity validation failures.",
            unit: "count",
            category: MetricCategory::Ops,
            severity: MetricSeverity::High,
            stability: MetricStability::Stable,
            labels: &["artifact_type", "failure_class"],
            cardinality_budget: 70,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-ARTIFACT-REGISTRY-ACCESS-001",
            name: "atlas_artifact_registry_access_seconds",
            description: "Artifact registry access time.",
            unit: "seconds",
            category: MetricCategory::Ops,
            severity: MetricSeverity::Medium,
            stability: MetricStability::Stable,
            labels: &["operation"],
            cardinality_budget: 40,
            version: "1.0.0",
        },
        MetricMetadata {
            id: "MET-ARTIFACT-VERIFY-COUNT-001",
            name: "atlas_artifact_verification_total",
            description: "Artifact verification operation count.",
            unit: "count",
            category: MetricCategory::Ops,
            severity: MetricSeverity::Low,
            stability: MetricStability::Stable,
            labels: &["artifact_type", "result"],
            cardinality_budget: 70,
            version: "1.0.0",
        },
    ];
    rows.sort_by(|a, b| a.id.cmp(b.id));
    rows
}
