from __future__ import annotations

import json
from pathlib import Path


def render_md(payload: dict[str, object]) -> str:
    kind = str(payload["kind"])
    lines = [f"# {kind.title()} Inventory", "", "Generated by `bijux-atlas inventory`.", ""]
    if kind == "make":
        lines += ["| Target | Area | Description |", "|---|---|---|"]
        lines += [f"| `{row['name']}` | `{row['area']}` | {row['description']} |" for row in payload.get("targets", [])]
    elif kind == "ops":
        lines += ["## Make Targets", ""] + [f"- `{item}`" for item in payload.get("make_targets", [])] + ["", "## Run Commands", ""]
        lines += [f"- `{item}`" for item in payload.get("ops_run_commands", [])]
    elif kind in {"configs", "schemas"}:
        lines += [f"- `{item}`" for item in payload.get("files", [])]
    elif kind == "owners":
        for src, data in payload.get("sources", {}).items():
            lines += [f"## `{src}`", "", f"- entries: `{len(data)}`", ""]
    elif kind == "contracts":
        lines += ["## CONTRACT.md", ""] + [f"- `{item}`" for item in payload.get("contract_files", [])] + ["", "## Schemas", ""]
        lines += [f"- `{item}`" for item in payload.get("schema_files", [])]
    elif kind == "budgets":
        lines += [f"- `{k}`: `{v}`" for k, v in payload.get("counts", {}).items()]
    elif kind == "commands":
        lines += [f"- total: `{payload.get('count', 0)}`", "", "| Command | Stable | Help |", "|---|---|---|"]
        lines += [f"| `{r['name']}` | `{r['stable']}` | {r['help']} |" for r in payload.get("commands", [])]
    elif kind == "touched-paths":
        lines += [f"- command: `{payload.get('command', '')}`", ""] + [f"- `{item}`" for item in payload.get("paths", [])]
    return "\n".join(lines) + "\n"


def outputs_for(kind: str) -> tuple[Path, Path]:
    mapping = {
        "make": (Path("make-targets.json"), Path("make-targets.md")),
        "ops": (Path("ops-surface.json"), Path("ops-surface.md")),
        "configs": (Path("configs-surface.json"), Path("configs-surface.md")),
        "schemas": (Path("schema-index.json"), Path("schema-index.md")),
        "owners": (Path("ownership.json"), Path("ownership.md")),
        "contracts": (Path("contracts-index.json"), Path("contracts-index.md")),
        "budgets": (Path("inventory-budgets.json"), Path("inventory-budgets.md")),
        "commands": (Path("commands.json"), Path("commands.md")),
        "touched-paths": (Path("touched-paths.json"), Path("touched-paths.md")),
    }
    return mapping[kind]


def validate_json_schema(repo_root: Path, kind: str, payload: dict[str, object]) -> None:
    import jsonschema

    schema = json.loads((repo_root / f"configs/contracts/inventory-{kind}.schema.json").read_text(encoding="utf-8"))
    jsonschema.validate(payload, schema)
