#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[8]

CORE_DOMAINS = ("stack", "k8s", "obs", "load", "e2e", "datasets", "report")


def _list_jsons(root: Path, rel: str) -> list[str]:
    base = root / rel
    if not base.exists():
        return []
    return sorted(p.relative_to(root).as_posix() for p in base.rglob("*.json") if p.is_file())


def _list_schemas(root: Path, domain: str) -> list[str]:
    base = root / "ops" / "schema" / domain
    if not base.exists():
        return []
    return sorted(p.relative_to(root).as_posix() for p in base.rglob("*.schema.json") if p.is_file())


def _domain_index(root: Path, domain: str) -> str:
    prefix = f"ops/{domain}"
    lines = [
        f"# {domain.capitalize()} Index",
        "",
        "Generated by `atlasctl ops gen index`. Do not edit manually.",
        "",
        "## Required Docs",
        "",
    ]
    for name in ("CONTRACT.md", "INDEX.md", "OWNER.md", "README.md"):
        path = root / prefix / name
        marker = "present" if path.exists() else "missing"
        lines.append(f"- `{prefix}/{name}` ({marker})")
    lines += ["", "## Manifests", ""]
    manifests = _list_jsons(root, prefix)
    if manifests:
        lines.extend(f"- `{m}`" for m in manifests if "/suites/" not in m)
    else:
        lines.append("- (none)")
    lines += ["", "## Suites", ""]
    suites = [m for m in manifests if "/suites/" in m]
    if suites:
        lines.extend(f"- `{m}`" for m in suites)
    else:
        lines.append("- (none)")
    lines += ["", "## Schemas", ""]
    schemas = _list_schemas(root, domain)
    if schemas:
        lines.extend(f"- `{s}`" for s in schemas)
    else:
        lines.append("- (none)")
    lines.append("")
    return "\n".join(lines)


def render_indexes(root: Path) -> dict[str, str]:
    outputs: dict[str, str] = {}
    for domain in CORE_DOMAINS:
        outputs[f"ops/{domain}/INDEX.md"] = _domain_index(root, domain)
    lines = [
        "# Ops Generated Index",
        "",
        "Generated by `atlasctl ops gen index`. Do not edit manually.",
        "",
        "## Domains",
        "",
    ]
    for domain in CORE_DOMAINS:
        lines.append(f"- `ops/{domain}/INDEX.md`")
    lines += ["", "## Core Metadata", ""]
    for rel in ("ops/inventory/surfaces.json", "configs/ops/public-surface.json", "configs/ops/suites.json"):
        lines.append(f"- `{rel}`")
    lines.append("")
    outputs["ops/_generated/INDEX.md"] = "\n".join(lines)
    return outputs


def main() -> int:
    expected = render_indexes(ROOT)
    drift: list[str] = []
    for rel, text in sorted(expected.items()):
        path = ROOT / rel
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != text:
            drift.append(rel)
    if drift:
        print("ops INDEX generated drift detected:", file=sys.stderr)
        for rel in drift:
            print(f"- {rel}", file=sys.stderr)
        print("run: ./bin/atlasctl ops gen index --i-know-what-im-doing", file=sys.stderr)
        return 1
    print("ops INDEX generated check passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
