// SPDX-License-Identifier: Apache-2.0

use bijux_dev_atlas::contracts::system_invariants::{registry, InvariantSeverity};
use std::fs;
use std::path::PathBuf;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace")
        .parent()
        .expect("repo")
        .to_path_buf()
}

#[test]
fn invariant_registry_ids_match_stable_snapshot() {
    let ids = registry()
        .into_iter()
        .map(|row| row.id.to_string())
        .collect::<Vec<_>>();
    let golden: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(
            repo_root().join("crates/bijux-dev-atlas/tests/goldens/system_invariant_registry_snapshot.json"),
        )
        .expect("read golden"),
    )
    .expect("parse golden");
    let expected = golden
        .get("invariant_ids")
        .and_then(serde_json::Value::as_array)
        .expect("invariant_ids");
    let expected = expected
        .iter()
        .filter_map(|v| v.as_str().map(str::to_string))
        .collect::<Vec<_>>();
    assert_eq!(ids, expected, "invariant IDs must stay stable");
}

#[test]
fn invariant_registry_is_documented_and_human_readable() {
    let docs = fs::read_to_string(repo_root().join("docs/operations/system-invariants-reference.md"))
        .expect("docs page");
    assert!(
        docs.contains("Generated by `bijux-dev-atlas invariants docs`."),
        "invariant registry documentation generator marker must exist"
    );
    for row in registry() {
        assert!(
            !row.title.trim().is_empty() && row.title.contains(' '),
            "invariant title must be human-readable: {}",
            row.id
        );
        assert!(
            !row.summary.trim().is_empty() && row.summary.contains(' '),
            "invariant summary must be human-readable: {}",
            row.id
        );
        match row.severity {
            InvariantSeverity::Critical | InvariantSeverity::High | InvariantSeverity::Medium => {}
        }
    }
}
