// SPDX-License-Identifier: Apache-2.0

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace")
        .parent()
        .expect("repo")
        .to_path_buf()
}

fn collect_markdown_files(dir: &Path, files: &mut Vec<PathBuf>) {
    let entries = fs::read_dir(dir).expect("read dir");
    for entry in entries {
        let path = entry.expect("entry").path();
        if path.is_dir() {
            collect_markdown_files(&path, files);
            continue;
        }
        if path.extension().and_then(|v| v.to_str()) == Some("md") {
            files.push(path);
        }
    }
}

#[test]
fn tutorials_should_not_embed_long_raw_output_blocks() {
    const MAX_INLINE_LINES: usize = 80;

    let root = repo_root();
    let tutorials = root.join("docs/tutorials");
    let mut files = Vec::new();
    collect_markdown_files(&tutorials, &mut files);

    let mut violations = Vec::new();
    for file in files {
        let text = fs::read_to_string(&file).expect("read markdown");
        let mut in_block = false;
        let mut block_lines = 0usize;
        let mut block_lang = String::new();

        for line in text.lines() {
            if line.starts_with("```") {
                if in_block {
                    if (block_lang == "text" || block_lang == "json" || block_lang == "bash")
                        && block_lines > MAX_INLINE_LINES
                    {
                        violations.push(format!(
                            "{} has inline `{}` block with {} lines (max {})",
                            file.strip_prefix(&root).unwrap_or(&file).display(),
                            block_lang,
                            block_lines,
                            MAX_INLINE_LINES
                        ));
                    }
                    in_block = false;
                    block_lines = 0;
                    block_lang.clear();
                } else {
                    in_block = true;
                    block_lang = line.trim_start_matches("```").trim().to_string();
                    block_lines = 0;
                }
                continue;
            }
            if in_block {
                block_lines += 1;
            }
        }
    }

    assert!(
        violations.is_empty(),
        "tutorials must reference generated snippets instead of long pasted command output:\n{}",
        violations.join("\n")
    );
}

#[test]
fn generated_docs_directory_contains_required_example_snippets() {
    let root = repo_root();
    let required = [
        "docs/_generated/examples.md",
        "docs/_generated/command-lists.md",
        "docs/_generated/schema-snippets.md",
        "docs/_generated/openapi-snippets.md",
        "docs/_generated/ops-snippets.md",
    ];
    let missing = required
        .iter()
        .filter(|rel| !root.join(rel).exists())
        .map(|rel| (*rel).to_string())
        .collect::<Vec<_>>();
    assert!(
        missing.is_empty(),
        "required generated tutorial snippets are missing: {}",
        missing.join(", ")
    );
}

#[test]
fn generated_docs_files_keep_autogenerated_header_marker() {
    let root = repo_root();
    let generated = root.join("docs/_generated");
    let mut violations = Vec::new();
    for entry in fs::read_dir(&generated).expect("read docs/_generated") {
        let path = entry.expect("entry").path();
        if path.extension().and_then(|v| v.to_str()) != Some("md") {
            continue;
        }
        let text = fs::read_to_string(&path).expect("read generated file");
        if !text.starts_with("<!-- autogenerated: bijux-dev-atlas docs generate -->") {
            violations.push(
                path.strip_prefix(&root)
                    .expect("relative path")
                    .display()
                    .to_string(),
            );
        }
    }
    assert!(
        violations.is_empty(),
        "generated docs files must keep generator header marker:\n{}",
        violations.join("\n")
    );
}

#[test]
fn every_generated_docs_markdown_file_is_referenced_by_docs_pages() {
    let root = repo_root();
    let docs = root.join("docs");
    let generated = root.join("docs/_generated");

    let mut docs_files = Vec::new();
    collect_markdown_files(&docs, &mut docs_files);
    let docs_text = docs_files
        .iter()
        .map(|path| fs::read_to_string(path).expect("read docs markdown"))
        .collect::<Vec<_>>()
        .join("\n");

    let mut orphaned = Vec::new();
    for entry in fs::read_dir(&generated).expect("read docs/_generated") {
        let path = entry.expect("entry").path();
        if path.extension().and_then(|v| v.to_str()) != Some("md") {
            continue;
        }
        let rel = path
            .strip_prefix(&root)
            .expect("relative path")
            .display()
            .to_string();
        let basename = path.file_name().and_then(|v| v.to_str()).expect("basename");
        let include_marker = format!("--8<-- \"{rel}\"");
        let rel_link = format!("../_generated/{basename}");
        if !docs_text.contains(&include_marker)
            && !docs_text.contains(&rel)
            && !docs_text.contains(&rel_link)
        {
            orphaned.push(rel);
        }
    }

    assert!(
        orphaned.is_empty(),
        "generated docs markdown files must be referenced from docs pages:\n{}",
        orphaned.join("\n")
    );
}

#[test]
fn generated_docs_file_set_matches_expected_snapshot() {
    let root = repo_root();
    let generated = root.join("docs/_generated");
    let mut files = fs::read_dir(&generated)
        .expect("read docs/_generated")
        .filter_map(|entry| {
            let path = entry.ok()?.path();
            if path.extension().and_then(|v| v.to_str()) != Some("md") {
                return None;
            }
            Some(
                path.strip_prefix(&root)
                    .expect("relative path")
                    .display()
                    .to_string(),
            )
        })
        .collect::<Vec<_>>();
    files.sort();
    let expected = vec![
        "docs/_generated/command-lists.md".to_string(),
        "docs/_generated/examples.md".to_string(),
        "docs/_generated/openapi-snippets.md".to_string(),
        "docs/_generated/ops-snippets.md".to_string(),
        "docs/_generated/schema-snippets.md".to_string(),
    ];
    assert_eq!(
        files, expected,
        "docs/_generated markdown set changed; update contracts and tutorial references"
    );
}

#[test]
fn slow_docs_verify_generated_reports_clean_state() {
    let output = Command::new(env!("CARGO_BIN_EXE_bijux-dev-atlas"))
        .current_dir(repo_root())
        .args(["docs", "verify-generated", "--format", "json"])
        .output()
        .expect("run docs verify-generated");
    assert!(
        output.status.success(),
        "docs verify-generated must pass for committed generated docs"
    );
    let payload: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("parse docs verify-generated json");
    assert_eq!(payload["status"], "ok");
    assert_eq!(
        payload["stale"].as_array().expect("stale array").len(),
        0,
        "docs verify-generated reported stale generated docs"
    );
}
