[build]
target-dir = "artifacts/target"

[alias]
fmt-check = "fmt --all -- --check --config-path configs/sources/repository/rust-tooling/rustfmt.toml"
lint = "clippy -p bijux-dev-atlas --all-targets --all-features --locked --no-deps -- -D warnings"
check-workspace = "check --workspace --all-targets"

[target.'cfg(target_os = "linux")']
rustflags = [
  "-C", "debuginfo=1",
  "-C", "link-arg=-Wl,-z,relro",
  "-C", "link-arg=-Wl,-z,now",
]

[target.'cfg(target_os = "macos")']
rustflags = [
  "-C", "debuginfo=1",
  "-C", "link-arg=-Wl,-dead_strip",
]

[term]
verbose = false
