kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: bijux-atlas-e2e
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 16443
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 18080
        protocol: TCP
      - containerPort: 30443
        hostPort: 18443
        protocol: TCP
      - containerPort: 30900
        hostPort: 19090
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            eviction-hard: "memory.available<100Mi,nodefs.available<5%"
            max-pods: "110"
