# Scope: shared deterministic environment defaults for make.
# Public targets: none
SHELL := /bin/sh

# Shared environment defaults for deterministic make runs.
MAKE_PRIMARY_GOAL ?= $(if $(MAKECMDGOALS),$(firstword $(MAKECMDGOALS)),help)
MAKE_RUN_TS ?= $(shell date -u +%Y%m%dT%H%M%SZ)
MAKE_RUN_ID ?= $(MAKE_PRIMARY_GOAL)-$(MAKE_RUN_TS)-$(shell sh -c 'echo $$PPID')
WORKSPACE_ROOT ?= $(abspath .)

ISO_ROOT ?= $(WORKSPACE_ROOT)/artifacts/isolate/$(MAKE_PRIMARY_GOAL)
ISO_ROOT := $(abspath $(ISO_ROOT))
ISO_RUN_ID ?= $(MAKE_RUN_ID)
ISO_TAG ?= $(MAKE_RUN_ID)
CARGO_TARGET_DIR ?= $(ISO_ROOT)/target
CARGO_HOME ?= $(ISO_ROOT)/cargo-home
NEXTEST_CACHE_DIR ?= $(ISO_ROOT)/nextest-cache
TMPDIR ?= $(ISO_ROOT)/tmp
TMP ?= $(TMPDIR)
TEMP ?= $(TMPDIR)
CARGO_TARGET_DIR := $(abspath $(CARGO_TARGET_DIR))
CARGO_HOME := $(abspath $(CARGO_HOME))
NEXTEST_CACHE_DIR := $(abspath $(NEXTEST_CACHE_DIR))
TMPDIR := $(abspath $(TMPDIR))
TMP := $(abspath $(TMP))
TEMP := $(abspath $(TEMP))

ATLAS_BASE_URL ?= http://127.0.0.1:18080
OPS_RUN_ID ?= atlas-ops-$(shell date -u +%Y%m%d-%H%M%S)
OPS_NAMESPACE ?= $(OPS_RUN_ID)
ATLAS_NS ?= $(OPS_NAMESPACE)
ATLAS_VALUES_FILE ?= ops/k8s/values/local.yaml
ATLAS_OFFLINE_VALUES_FILE ?= ops/k8s/values/offline.yaml
ATLAS_PERF_VALUES_FILE ?= ops/k8s/values/perf.yaml
ATLAS_MULTI_REGISTRY_VALUES_FILE ?= ops/k8s/values/multi-registry.yaml
ATLAS_INGRESS_VALUES_FILE ?= ops/k8s/values/ingress.yaml
ATLAS_RUN_ID ?= $(OPS_RUN_ID)
ATLAS_E2E_TIMEOUT ?= 180s
ATLAS_E2E_ENABLE_REDIS ?= 0
ATLAS_E2E_ENABLE_OTEL ?= 1
ATLAS_E2E_ENABLE_TOXIPROXY ?= 0
ATLAS_E2E_TEST_GROUP ?=
ATLAS_E2E_TEST ?=
ATLAS_E2E_CLUSTER_NAME ?= bijux-atlas-e2e
OPS_RUN_DIR ?= artifacts/ops/$(OPS_RUN_ID)
RUN_ID ?= $(OPS_RUN_ID)
ARTIFACT_DIR ?= $(OPS_RUN_DIR)
QUIET ?= 0

export MAKE_PRIMARY_GOAL MAKE_RUN_TS MAKE_RUN_ID
export ISO_ROOT ISO_RUN_ID ISO_TAG CARGO_TARGET_DIR CARGO_HOME NEXTEST_CACHE_DIR TMPDIR TMP TEMP
export ATLAS_BASE_URL ATLAS_NS ATLAS_VALUES_FILE ATLAS_OFFLINE_VALUES_FILE
export ATLAS_PERF_VALUES_FILE ATLAS_MULTI_REGISTRY_VALUES_FILE ATLAS_INGRESS_VALUES_FILE
export ATLAS_RUN_ID ATLAS_E2E_TIMEOUT ATLAS_E2E_ENABLE_REDIS ATLAS_E2E_ENABLE_OTEL
export ATLAS_E2E_ENABLE_TOXIPROXY ATLAS_E2E_TEST_GROUP ATLAS_E2E_TEST
export ATLAS_E2E_CLUSTER_NAME
export ATLAS_E2E_NAMESPACE ?= $(ATLAS_NS)
export ATLAS_E2E_VALUES_FILE ?= $(ATLAS_VALUES_FILE)
export OPS_RUN_ID OPS_NAMESPACE OPS_RUN_DIR
export RUN_ID ARTIFACT_DIR
export QUIET
