SHELL := /bin/sh

# Shared environment defaults for deterministic make runs.
MAKE_PRIMARY_GOAL ?= $(if $(MAKECMDGOALS),$(firstword $(MAKECMDGOALS)),help)
MAKE_RUN_TS ?= $(shell date -u +%Y%m%dT%H%M%SZ)
MAKE_RUN_ID ?= $(MAKE_PRIMARY_GOAL)-$(MAKE_RUN_TS)-$(shell sh -c 'echo $$PPID')

ISO_ROOT ?= artifacts/isolates/$(MAKE_PRIMARY_GOAL)
ISO_TAG ?= $(MAKE_RUN_ID)
CARGO_TARGET_DIR ?= $(ISO_ROOT)/target
CARGO_HOME ?= $(ISO_ROOT)/cargo-home
TMPDIR ?= $(ISO_ROOT)/tmp
TMP ?= $(TMPDIR)
TEMP ?= $(TMPDIR)

ATLAS_BASE_URL ?= http://127.0.0.1:18080
ATLAS_NS ?= atlas-e2e
ATLAS_VALUES_FILE ?= ops/k8s/values/local.yaml
ATLAS_OFFLINE_VALUES_FILE ?= ops/k8s/values/offline.yaml
ATLAS_PERF_VALUES_FILE ?= ops/k8s/values/perf.yaml
ATLAS_MULTI_REGISTRY_VALUES_FILE ?= ops/k8s/values/multi-registry.yaml
ATLAS_INGRESS_VALUES_FILE ?= ops/k8s/values/ingress.yaml
ATLAS_RUN_ID ?= local
ATLAS_E2E_TIMEOUT ?= 180s
ATLAS_E2E_ENABLE_REDIS ?= 0
ATLAS_E2E_ENABLE_OTEL ?= 0
ATLAS_E2E_ENABLE_TOXIPROXY ?= 0
ATLAS_E2E_TEST_GROUP ?=
ATLAS_E2E_TEST ?=
OPS_RUN_ID ?= $(ATLAS_RUN_ID)
OPS_RUN_DIR ?= artifacts/ops/$(OPS_RUN_ID)

export MAKE_PRIMARY_GOAL MAKE_RUN_TS MAKE_RUN_ID
export ISO_ROOT ISO_TAG CARGO_TARGET_DIR CARGO_HOME TMPDIR TMP TEMP
export ATLAS_BASE_URL ATLAS_NS ATLAS_VALUES_FILE ATLAS_OFFLINE_VALUES_FILE
export ATLAS_PERF_VALUES_FILE ATLAS_MULTI_REGISTRY_VALUES_FILE ATLAS_INGRESS_VALUES_FILE
export ATLAS_RUN_ID ATLAS_E2E_TIMEOUT ATLAS_E2E_ENABLE_REDIS ATLAS_E2E_ENABLE_OTEL
export ATLAS_E2E_ENABLE_TOXIPROXY ATLAS_E2E_TEST_GROUP ATLAS_E2E_TEST
export ATLAS_E2E_NAMESPACE ?= $(ATLAS_NS)
export ATLAS_E2E_VALUES_FILE ?= $(ATLAS_VALUES_FILE)
export OPS_RUN_ID OPS_RUN_DIR
