from __future__ import annotations
from .native import (
    check_command_scripts_registry,
    check_config_generated_headers_and_checksums,
    check_config_generated_no_human_refs,
    check_config_lock_discipline,
    check_config_migration_cutoff_legacy_locations,
    check_docs_no_ops_generated_run_paths,
    check_duplicate_script_names,
    check_generated_dirs_policy,
    check_forbidden_top_dirs,
    check_migration_progress_regression,
    check_no_executable_python_outside_packages,
    check_no_direct_bash_invocations,
    check_no_direct_python_invocations,
    check_no_large_binary_files,
    check_cli_help_output_deterministic,
    check_json_output_deterministic_policy,
    check_no_models_shim_when_model_canonical,
    check_no_adhoc_python,
    check_no_direct_env_reads_outside_runtime_env,
    check_no_os_getcwd_outside_runtime_context,
    check_no_ops_generated_placeholder,
    check_no_repo_root_path_literals,
    check_no_xtask_refs,
    check_ops_inventory_schema_coverage,
    check_ops_examples_immutable,
    check_ops_helm_render_inventory_drift,
    check_ops_helm_versions_pinned,
    check_ops_images_pinned_to_digests_policy,
    check_ops_load_thresholds_exist_for_every_suite,
    check_ops_namespaces_inventory_manifest_agreement,
    check_ops_observability_assets_for_public_surfaces,
    check_ops_ports_and_surfaces_contract,
    check_ops_generated_tracked,
    check_ops_workflow_evidence_path_policy,
    check_repo_no_python_caches_committed,
    check_single_canonical_runtime_adapters,
    check_tmp_paths_outside_artifacts,
    check_ops_configs_deterministic_newlines,
    check_script_help,
    check_script_ownership,
    check_tracked_timestamp_paths,
    check_makefiles_no_deep_config_paths,
)
from ...model import CheckDef
from .enforcement.legacy_guard import check_legacy_package_absent
from ....commands.policies.runtime.culprits import (
    check_budget_drift_approval,
    check_critical_dir_count_trend,
    check_budget_exceptions_documented,
    check_budget_exceptions_sorted,
    check_budget_metric,
)
from ....commands.policies.runtime.dir_budgets import check_loc_per_dir, check_modules_per_dir, check_py_files_per_dir
from ....commands.policies.runtime.dir_entry_budgets import check_dir_entry_budgets, check_py_files_per_dir_budget
from ....commands.policies.runtime.module_budgets import check_modules_per_domain
from ....commands.policies.runtime.tree_depth import check_tree_depth
from .enforcement.cwd_usage import (
    check_no_environ_mutation,
    check_no_path_cwd_usage,
    check_no_path_dot_in_runtime,
)
from .contracts.command_contracts import (
    check_command_alias_budget,
    check_cli_canonical_paths,
    check_command_help_docs_drift,
    check_command_group_owners,
    check_command_metadata_contract,
    check_command_ownership_docs,
    check_command_surface_stability,
    check_internal_commands_not_public,
    check_network_default_deny_policy,
    check_no_deprecated_commands,
    check_no_duplicate_command_implementation_patterns,
    check_no_duplicate_command_names,
    check_no_legacy_command_names,
    check_no_undocumented_help_commands,
    check_public_commands_docs_index,
    check_registry_single_source,
    check_stable_command_no_breaking_changes,
)
from .enforcement.argparse_policy import check_argparse_policy
from .enforcement.structure.checks_tree_policy import check_checks_tree_policy
from .enforcement.package_shape import (
    check_atlasctl_package_root_shape,
    check_canonical_concept_homes,
    check_checks_domain_split,
    check_checks_root_contract,
    check_layout_domain_readmes,
    check_layout_no_legacy_imports,
    check_module_size,
    check_no_nested_same_name_packages,
    check_top_level_package_group_mapping,
)
from .enforcement.structure.check_top_level_structure import check_top_level_structure
from .enforcement.structure.check_structure import (
    check_cli_main_loc_budget,
    check_check_impl_no_cli_imports,
    check_checks_canonical_location,
    check_main_entrypoint_calls_app_main,
    check_registry_generated_readonly,
)
from .enforcement.package_hygiene import (
    check_folder_intent_contract,
    check_no_empty_dirs_or_pointless_nests,
    check_no_empty_packages,
    check_no_placeholder_module_names,
    check_package_has_module_or_readme,
)
from .enforcement.shell_policy import (
    check_core_no_bash_subprocess,
    check_no_layout_shadow_configs,
    check_shell_docs_present,
    check_shell_no_network_download_tools,
    check_shell_headers_and_strict_mode,
    check_shell_invocation_via_core_exec,
    check_shell_location_policy,
    check_shell_no_python_direct_calls,
    check_shell_script_budget,
    check_shell_scripts_readonly,
)
from .domains.scripts_dir import check_scripts_dir_absent
from .contracts.public_api import check_public_api_exports
from .contracts.naming_hygiene import (
    check_command_module_cli_intent,
    check_contracts_namespace_purpose,
    check_layout_domain_alias_cleanup,
    check_no_wildcard_exports,
    check_public_api_doc_exists,
    check_single_registry_module,
    check_single_runner_module,
)
from .contracts.type_coverage import check_type_coverage
from .contracts.dependencies import (
    check_dependency_declarations,
    check_internal_utils_stdlib_only,
    check_optional_dependency_usage_gates,
)
from .domains.policies import check_forbidden_adjectives
from ..reachability import (
    check_dead_module_reachability_allowlist,
    check_dead_modules_report_runs,
    check_no_legacy_importers,
    check_repo_check_modules_registered,
)
from .contracts.required_proof import check_required_target_shape
from .enforcement.import_policy import (
    check_cli_import_scope,
    check_cli_render_boundary,
    check_command_import_lint,
    check_commands_check_no_domain_imports,
    check_commands_no_check_impl_imports,
    check_core_no_command_imports,
    check_checks_import_lint,
    check_checks_no_commands_check_imports,
    check_checks_no_command_imports,
    check_checks_no_cli_imports,
    check_contract_import_boundaries,
    check_cold_import_budget,
    check_compileall_gate,
    check_forbidden_core_integration_dir,
    check_forbidden_deprecated_namespace_dirs,
    check_forbidden_deprecated_namespaces,
    check_import_smoke,
    check_internal_import_boundaries,
    check_no_legacy_module_paths,
    check_no_legacy_obs_imports_in_modern,
    check_no_modern_imports_from_legacy,
    check_registry_definition_boundary,
    check_runcontext_single_builder,
)
from .enforcement.boundaries.effect_boundaries import (
    check_effect_boundary_exceptions_policy,
    check_forbidden_effect_calls,
    check_managed_artifact_write_roots,
    check_subprocess_boundary,
)
from .contracts.pyproject_contracts import (
    check_dependency_gate_targets,
    check_deps_workflow_doc,
    check_deps_command_surface,
    check_dependency_owner_justification,
    check_console_script_entry,
    check_env_docs_present,
    check_optional_dependency_groups,
    check_packaging_metadata_completeness,
    check_python_requires_version_and_ci,
    check_pyproject_minimalism,
    check_pyproject_no_duplicate_tool_config,
    check_pyproject_required_blocks,
    check_python_module_help,
    check_requirements_artifact_policy,
    check_requirements_sync_with_pyproject,
    check_version_matches_pyproject,
)
from .native.workflow_contracts import (
    check_ci_artifact_upload_policy,
    check_ci_workflow_policy,
    check_workflows_targets_exist,
)
from .contracts.suite_inventory import check_suite_inventory_policy
from .contracts.test_guardrails import (
    check_check_test_coverage,
    check_command_test_coverage,
    check_duplicate_contract_assertions,
    check_json_goldens_validate_schema,
    check_no_duplicated_coverage_paths,
    check_no_conflicting_json_goldens,
    check_output_format_stability,
    check_no_unmarked_test_network,
    check_no_unjustified_skips,
    check_suite_marker_rules,
    check_test_determinism_patterns,
    check_test_duplicate_expectations,
    check_test_ownership_tags,
    check_test_taxonomy_layout,
    check_test_write_sandbox,
)
from .root_forbidden_files import (
    CHECK_ID as FORBIDDEN_ROOT_FILES_CHECK_ID,
    DESCRIPTION as FORBIDDEN_ROOT_FILES_DESCRIPTION,
    run as run_forbidden_root_files,
)
from .root_forbidden_names import (
    CHECK_ID as FORBIDDEN_ROOT_NAMES_CHECK_ID,
    DESCRIPTION as FORBIDDEN_ROOT_NAMES_DESCRIPTION,
    run as run_forbidden_root_names,
)
from .root_forbidden_paths import (
    CHECK_ID as FORBIDDEN_PATHS_CHECK_ID,
    DESCRIPTION as FORBIDDEN_PATHS_DESCRIPTION,
    run as run_forbidden_paths,
)
from .root_no_direct_script_runs import (
    CHECK_ID as DIRECT_SCRIPT_RUNS_CHECK_ID,
    DESCRIPTION as DIRECT_SCRIPT_RUNS_DESCRIPTION,
    run as run_no_direct_script_runs,
)
from .root_determinism import (
    CHECK_ID as ROOT_DETERMINISM_CHECK_ID,
    DESCRIPTION as ROOT_DETERMINISM_DESCRIPTION,
    run as run_root_determinism,
)
from .root_shape import (
    CHECK_ID as ROOT_SHAPE_CHECK_ID,
    DESCRIPTION as ROOT_SHAPE_DESCRIPTION,
    run as run_root_shape,
)

CHECKS: tuple[CheckDef, ...] = (
    CheckDef("repo.forbidden_top_dirs", "repo", "forbid top-level forbidden directories", 500, check_forbidden_top_dirs, fix_hint="Remove forbidden root directories."),
    CheckDef("repo.docs_no_ops_generated_refs", "repo", "disallow docs refs to ops generated runtime paths", 800, check_docs_no_ops_generated_run_paths, fix_hint="Replace generated runtime paths with canonical docs references."),
    CheckDef("repo.no_xtask_refs", "repo", "forbid xtask references", 1000, check_no_xtask_refs, fix_hint="Remove xtask references and use atlasctl workflows."),
    CheckDef("repo.no_exec_python_outside_packages", "repo", "forbid executable python outside package boundaries", 1500, check_no_executable_python_outside_packages, fix_hint="Move script into package module or remove executable bit."),
    CheckDef("repo.no_direct_python_invocations", "repo", "forbid direct python script calls in docs/makefiles", 1000, check_no_direct_python_invocations, fix_hint="Use atlasctl command entrypoints instead of python path/to/script.py."),
    CheckDef("repo.no_direct_bash_invocations", "repo", "forbid direct bash script calls in docs/makefiles", 1000, check_no_direct_bash_invocations, fix_hint="Use atlasctl commands instead of bash scripts/... invocations."),
    CheckDef("repo.no_adhoc_python", "repo", "forbid ad-hoc python files outside package boundaries", 1200, check_no_adhoc_python, fix_hint="Migrate ad-hoc python files into package modules."),
    CheckDef("repo.forbidden_adjectives", "repo", "forbid banned wording across tracked repository files", 500, check_forbidden_adjectives, fix_hint="Replace banned wording or add explicit approval entries in configs/policy/forbidden-adjectives-approvals.json."),
    CheckDef("repo.no_tracked_ops_generated", "repo", "ensure ops/_generated has no tracked files", 1000, check_ops_generated_tracked, fix_hint="Untrack generated files and add to ignore policy.", effects=("subprocess",)),
    CheckDef("repo.no_ops_generated_placeholder", "repo", "forbid placeholder generated dirs", 400, check_no_ops_generated_placeholder, fix_hint="Remove placeholder generated files/directories."),
    CheckDef("repo.ops_examples_immutable", "repo", "enforce immutability of ops examples", 800, check_ops_examples_immutable, fix_hint="Restore example fixtures to committed canonical content."),
    CheckDef("repo.no_tracked_timestamp_paths", "repo", "forbid timestamp-like tracked paths", 1000, check_tracked_timestamp_paths, fix_hint="Remove timestamped tracked files/dirs.", effects=("subprocess",)),
    CheckDef("repo.no_python_caches_committed", "repo", "forbid committed python caches under packages/atlasctl", 1000, check_repo_no_python_caches_committed, fix_hint="Remove tracked __pycache__/.pyc/.pytest_cache files and keep them ignored.", effects=("subprocess",)),
    CheckDef("repo.generated_dirs_policy", "repo", "enforce canonical generated dirs list", 600, check_generated_dirs_policy, fix_hint="Keep generated dirs to canonical locations (docs/_generated, ops/_generated, ops/_generated.example, artifacts/*)."),
    CheckDef("repo.tmp_paths_under_artifacts", "repo", "forbid committed tmp paths outside artifacts/", 800, check_tmp_paths_outside_artifacts, fix_hint="Move tmp paths under artifacts/ or rename to a durable path."),
    CheckDef("repo.ops_configs_newline_policy", "repo", "enforce LF-only and no trailing whitespace in ops/configs text files", 500, check_ops_configs_deterministic_newlines, fix_hint="Normalize files to LF and remove trailing whitespace.", effects=("subprocess",)),
    CheckDef("repo.no_large_binary_files", "repo", "forbid large tracked binary files except approved fixtures", 800, check_no_large_binary_files, fix_hint="Store large binaries outside git or document approved fixture exceptions.", effects=("subprocess",)),
    CheckDef("repo.cli_help_deterministic", "repo", "ensure atlasctl CLI help output is deterministic", 300, check_cli_help_output_deterministic, fix_hint="Keep CLI help generation stable and free of timestamps."),
    CheckDef("repo.json_output_deterministic_policy", "repo", "enforce deterministic json.dumps sort_keys policy", 900, check_json_output_deterministic_policy, fix_hint="Use core/runtime/serialize.dumps_json or pass sort_keys=True to json.dumps."),
    CheckDef("repo.no_models_shim_when_model_canonical", "repo", "forbid `models` shim modules when canonical package is `model`", 400, check_no_models_shim_when_model_canonical, fix_hint="Migrate imports/usages to `core/model` and remove `models` compatibility modules."),
    CheckDef("repo.single_canonical_runtime_adapters", "repo", "enforce one canonical runtime adapter module per capability", 400, check_single_canonical_runtime_adapters, fix_hint="Keep a single canonical paths/exec/exec_shell/network module and mark temporary facades as LEGACY."),
    CheckDef("repo.no_os_getcwd_outside_runtime_context", "repo", "forbid os.getcwd outside runtime context resolution", 300, check_no_os_getcwd_outside_runtime_context, fix_hint="Resolve cwd via runtime context/paths and add temporary allowlist entries only during migration."),
    CheckDef("repo.no_direct_env_reads_outside_runtime_env", "repo", "forbid direct env reads outside runtime env module", 300, check_no_direct_env_reads_outside_runtime_env, fix_hint="Use atlasctl runtime env helpers; only temporary allowlisted legacy callsites are permitted."),
    CheckDef("repo.no_repo_root_path_literals", "repo", "forbid repo-root Path literals outside runtime paths/context", 300, check_no_repo_root_path_literals, fix_hint="Use runtime paths/context instead of Path(\"configs/...\"), Path(\"ops/...\"), etc."),
    CheckDef("repo.duplicate_script_names", "repo", "forbid duplicate script stem names", 1200, check_duplicate_script_names, fix_hint="Rename colliding script names."),
    CheckDef("repo.script_help_coverage", "repo", "validate script help contract coverage", 1500, check_script_help, fix_hint="Add --help contract output to required scripts."),
    CheckDef("repo.script_ownership_coverage", "repo", "validate script ownership coverage", 1500, check_script_ownership, fix_hint="Update ownership metadata for uncovered scripts."),
    CheckDef("repo.migration_progress_regression", "repo", "forbid migration progress regression (no new legacy patterns)", 600, check_migration_progress_regression, fix_hint="Use ./bin/atlasctl in docs/makefiles and remove legacy migration wording."),
    CheckDef("repo.command_scripts_registry", "repo", "enforce command-invoked shell scripts are registered with owner and valid naming", 1000, check_command_scripts_registry, fix_hint="Register every command-invoked .sh in configs/scripts/registry.json with valid owner and naming."),
    CheckDef("repo.no_scripts_dir", "repo", "forbid legacy root scripts dir", 250, check_scripts_dir_absent, fix_hint="Migrate scripts into atlasctl package commands."),
    CheckDef("repo.legacy_package_absent", "repo", "require atlasctl legacy package to be absent", 250, check_legacy_package_absent, fix_hint="Delete packages/atlasctl/src/atlasctl/legacy and migrate importers."),
    CheckDef("repo.module_size", "repo", "enforce module size budget", 400, check_module_size, fix_hint="Split oversized modules into focused submodules."),
    CheckDef("repo.dir_budget_modules", "repo", "enforce per-directory python module count budget", 400, check_modules_per_dir, fix_hint="Split high-density directories into intent-focused subpackages."),
    CheckDef("repo.dir_budget_py_files", "repo", "enforce per-directory python file count budget", 400, check_py_files_per_dir, fix_hint="Split high-density directories and keep directory fan-in bounded."),
    CheckDef(
        "repo.dir_budget_entries",
        "repo",
        "enforce per-directory entries budget in atlasctl src/tests",
        400,
        check_dir_entry_budgets,
        fix_hint="Split crowded directories; required reading: packages/atlasctl/docs/architecture/how-to-split-a-module.md.",
    ),
    CheckDef(
        "repo.dir_budget_py_scope",
        "repo",
        "enforce per-directory .py file budget in atlasctl src/tests (excluding __init__.py)",
        400,
        check_py_files_per_dir_budget,
        fix_hint="Split module directories and keep <=10 python files per dir; see how-to-split-a-module.md.",
    ),
    CheckDef(
        "repo.dir_budget_loc",
        "repo",
        "enforce per-directory total LOC budget",
        400,
        check_loc_per_dir,
        fix_hint="Move unrelated files into domain subpackages to reduce dir-level LOC density.",
    ),
    CheckDef(
        "repo.module_budget_domains",
        "repo",
        "enforce module count budget per top-level atlasctl domain",
        400,
        check_modules_per_domain,
        fix_hint="Split high-density top-level domains and relocate modules by control-plane ownership.",
    ),
    CheckDef(
        "repo.dir_budget_exceptions_documented",
        "repo",
        "ensure budget exceptions are documented",
        300,
        check_budget_exceptions_documented,
        fix_hint="Document each budget exception path in packages/atlasctl/docs/architecture.md.",
    ),
    CheckDef(
        "repo.dir_budget_exceptions_sorted",
        "repo",
        "ensure budget exceptions are sorted deterministically",
        300,
        check_budget_exceptions_sorted,
        fix_hint="Sort [[tool.atlasctl.budgets.exceptions]] entries by path in pyproject.toml.",
    ),
    CheckDef(
        "repo.budget_drift_approval",
        "repo",
        "forbid budget loosening without explicit approval marker",
        300,
        check_budget_drift_approval,
        fix_hint="Update configs/policy/atlasctl-budgets-baseline.json or add approved budget-loosening marker.",
    ),
    CheckDef(
        "repo.dir_count_trend_gate",
        "repo",
        "forbid critical directory file/module count drift above baseline",
        300,
        check_critical_dir_count_trend,
        fix_hint="Split critical directories or update configs/policy/atlasctl-dir-count-baseline.json with approval.",
    ),
    CheckDef(
        "repo.dir_budget_shell_files",
        "repo",
        "enforce per-directory shell file count budget",
        400,
        lambda repo_root: check_budget_metric(repo_root, "shell-files-per-dir"),
        fix_hint="Move shell scripts into approved layout/ops directories and split crowded directories.",
    ),
    CheckDef(
        "repo.file_import_budget",
        "repo",
        "enforce python import count budget per file",
        400,
        lambda repo_root: check_budget_metric(repo_root, "imports-per-file"),
        fix_hint="Reduce import fan-in and use lazy imports where needed.",
    ),
    CheckDef(
        "repo.file_public_symbol_budget",
        "repo",
        "enforce public symbol budget per module",
        400,
        lambda repo_root: check_budget_metric(repo_root, "public-symbols-per-file"),
        fix_hint="Split dumping-ground modules and narrow __all__ exports.",
    ),
    CheckDef(
        "repo.file_complexity_budget",
        "repo",
        "enforce complexity heuristic budget in core/cli",
        400,
        lambda repo_root: check_budget_metric(repo_root, "complexity-heuristic"),
        fix_hint="Split high-complexity control flow and extract focused helpers.",
    ),
    CheckDef(
        "repo.shell_location_policy",
        "repo",
        "forbid shell scripts under atlasctl python package tree",
        300,
        check_shell_location_policy,
        fix_hint="Move shell scripts to ops/vendor/layout-checks or port them to python.",
    ),
    CheckDef(
        "repo.shell_strict_mode",
        "repo",
        "require shell header and strict mode",
        300,
        check_shell_headers_and_strict_mode,
        fix_hint="Add #!/usr/bin/env bash and set -euo pipefail to all shell scripts.",
    ),
    CheckDef(
        "repo.shell_no_direct_python",
        "repo",
        "forbid direct python invocation in shell scripts",
        300,
        check_shell_no_python_direct_calls,
        fix_hint="Call atlasctl entrypoints instead of python commands in shell scripts.",
    ),
    CheckDef(
        "repo.shell_no_network_fetch",
        "repo",
        "forbid direct curl/wget usage in shell scripts",
        300,
        check_shell_no_network_download_tools,
        fix_hint="Use atlasctl-managed fetch entrypoints or explicit allow annotation.",
    ),
    CheckDef(
        "repo.shell_readonly_checks",
        "repo",
        "forbid direct file writes in layout shell checks",
        300,
        check_shell_scripts_readonly,
        fix_hint="Keep layout shell checks read-only and route outputs through stdout/stderr only.",
    ),
    CheckDef(
        "repo.shell_invocation_boundary",
        "repo",
        "forbid direct shell subprocess invocations outside core.exec",
        300,
        check_shell_invocation_via_core_exec,
        fix_hint="Route shell invocations through core.exec wrapper helpers.",
    ),
    CheckDef(
        "repo.core_no_bash_subprocess",
        "repo",
        "forbid subprocess.run(['bash'|'sh', ...]) in core logic",
        300,
        check_core_no_bash_subprocess,
        fix_hint="Use core.exec wrappers; do not invoke bash/sh directly in core.",
    ),
    CheckDef(
        "repo.shell_script_budget",
        "repo",
        "cap total shell script count in repository",
        300,
        check_shell_script_budget,
        fix_hint="Port shell scripts to Python modules and delete duplicates.",
    ),
    CheckDef(
        "repo.shell_docs_present",
        "repo",
        "require shell directory README and policy docs",
        300,
        check_shell_docs_present,
        fix_hint="Add README.md and POLICY.md under ops/vendor/layout-checks.",
    ),
    CheckDef(
        "repo.layout_no_shadow",
        "repo",
        "enforce no-shadow config policy",
        300,
        check_no_layout_shadow_configs,
        fix_hint="Resolve shadow config sources reported by atlasctl/layout/no_shadow.py.",
        effects=("subprocess",),
    ),
    CheckDef("repo.layout_domain_readmes", "repo", "ensure each layout check domain includes a README", 300, check_layout_domain_readmes, fix_hint="Add README.md to each checks/layout/<domain>/ directory."),
    CheckDef("repo.checks_domain_split", "repo", "require canonical check domain tree (repo_shape/makefiles/ops/docs/observability/artifacts)", 300, check_checks_domain_split, fix_hint="Create or migrate domain packages under packages/atlasctl/src/atlasctl/checks/."),
    CheckDef("repo.checks_root_contract", "repo", "enforce checks root contract (single python root file and module cap)", 300, check_checks_root_contract, fix_hint="Keep only __init__.py + registry artifacts at checks root and group modules under domain packages."),
    CheckDef(
        "repo.checks_tree_policy",
        "repo",
        "enforce checks tree depth, module-density budget, and naming hygiene",
        500,
        check_checks_tree_policy,
        fix_hint="Split oversized checks directories with `atlasctl dev split-module` and remove misc/utils or duplicated area segments.",
    ),
    CheckDef("repo.layout_no_legacy_imports", "repo", "forbid legacy imports in checks/layout modules", 300, check_layout_no_legacy_imports, fix_hint="Remove " + "atlasctl." + "legacy" + " imports from layout checks."),
    CheckDef("repo.top_level_structure", "repo", "enforce atlasctl top-level package intent and budget", 300, check_top_level_structure, fix_hint="Keep atlasctl top-level package set within STRUCTURE.md contract."),
    CheckDef(
        "repo.atlasctl_package_root_shape",
        "repo",
        "require atlasctl package root to contain only allowed files and directories",
        300,
        check_atlasctl_package_root_shape,
        fix_hint="Keep only LICENSE, README.md, docs/, pyproject.toml, src/, tests/ (+ optional requirements input/lock) in packages/atlasctl root.",
    ),
    CheckDef(
        "repo.top_level_package_group_mapping",
        "repo",
        "require top-level atlasctl packages to map to control-plane groups",
        300,
        check_top_level_package_group_mapping,
        fix_hint="Map new top-level packages to configs/dev/ops/policies/internal in package_shape policy.",
    ),
    CheckDef(
        "repo.package_max_depth",
        "repo",
        "enforce maximum atlasctl package nesting depth",
        300,
        check_tree_depth,
        fix_hint="Flatten deep package hierarchies under packages/atlasctl/src/atlasctl.",
    ),
    CheckDef(
        "repo.canonical_concept_homes",
        "repo",
        "forbid duplicate top-level concept packages for registry/runner/contracts/output",
        300,
        check_canonical_concept_homes,
        fix_hint="Keep only canonical concept homes: registry, suite, contracts, reporting.",
    ),
    CheckDef(ROOT_SHAPE_CHECK_ID, "repo", ROOT_SHAPE_DESCRIPTION, 500, run_root_shape, fix_hint="Align root entries with checks/tools/root_policy.json."),
    CheckDef(FORBIDDEN_ROOT_FILES_CHECK_ID, "repo", FORBIDDEN_ROOT_FILES_DESCRIPTION, 400, run_forbidden_root_files, fix_hint="Remove forbidden junk files from repository root."),
    CheckDef(FORBIDDEN_ROOT_NAMES_CHECK_ID, "repo", FORBIDDEN_ROOT_NAMES_DESCRIPTION, 400, run_forbidden_root_names, fix_hint="Remove forbidden top-level legacy names from repository root."),
    CheckDef(FORBIDDEN_PATHS_CHECK_ID, "repo", FORBIDDEN_PATHS_DESCRIPTION, 500, run_forbidden_paths, fix_hint="Remove forbidden legacy path references from make/docs/workflows."),
    CheckDef(DIRECT_SCRIPT_RUNS_CHECK_ID, "repo", DIRECT_SCRIPT_RUNS_DESCRIPTION, 500, run_no_direct_script_runs, fix_hint="Invoke workflows through make targets instead of direct scripts/ops paths."),
    CheckDef(ROOT_DETERMINISM_CHECK_ID, "repo", ROOT_DETERMINISM_DESCRIPTION, 1500, run_root_determinism, fix_hint="Stabilize generated root outputs so consecutive runs are identical.", slow=True),
    CheckDef(
        "repo.no_nested_same_name_packages",
        "repo",
        "forbid nested package segments with same name",
        300,
        check_no_nested_same_name_packages,
        fix_hint="Flatten nested same-name package segments (example: checks/checks).",
    ),
    CheckDef("repo.no_empty_packages", "repo", "forbid empty non-legacy packages without README", 300, check_no_empty_packages, fix_hint="Add a real module or README.md to package directories."),
    CheckDef("repo.no_empty_dirs_or_pointless_nests", "repo", "forbid empty directories and pointless single-child nesting under src/atlasctl", 300, check_no_empty_dirs_or_pointless_nests, fix_hint="Delete empty directories and flatten single-child nests without modules or README markers."),
    CheckDef(
        "repo.folder_intent_contract",
        "repo",
        "require intent marker for checks directories",
        300,
        check_folder_intent_contract,
        fix_hint="Add README.md or check_*.py module in each checks directory.",
    ),
    CheckDef("repo.no_placeholder_module_names", "repo", "forbid placeholder-like module filenames in modern code", 300, check_no_placeholder_module_names, fix_hint="Rename modules to intent-revealing names."),
    CheckDef("repo.package_has_module_or_readme", "repo", "require each non-legacy package to contain a module or README", 300, check_package_has_module_or_readme, fix_hint="Add module implementation or README.md to document empty package."),
    CheckDef("repo.no_path_cwd_usage", "repo", "forbid Path.cwd usage outside core.runtime.repo_root.py", 400, check_no_path_cwd_usage, fix_hint="Use ctx.repo_root or core.runtime.repo_root helpers."),
    CheckDef("repo.no_path_dot_runtime", "repo", "forbid dot-path usage in checks runtime", 400, check_no_path_dot_in_runtime, fix_hint="Resolve paths from explicit repo_root context instead of current-directory dot paths."),
    CheckDef("repo.no_environ_mutation", "repo", "forbid os.environ mutation in checks runtime", 400, check_no_environ_mutation, fix_hint="Pass environment values through context/capabilities and avoid mutating process env."),
    CheckDef("repo.command_metadata_contract", "repo", "ensure command metadata includes touches/tools/effect declarations", 400, check_command_metadata_contract, fix_hint="Add touches/tools/effect metadata in cli registry."),
    CheckDef("repo.network_default_deny", "repo", "enforce network-forbidden-by-default command policy", 300, check_network_default_deny_policy, fix_hint="Require explicit --allow-network for network-capable commands and keep default deny."),
    CheckDef("repo.argparse_policy", "repo", "restrict direct argparse parser construction to canonical parser modules", 300, check_argparse_policy, fix_hint="Move parser construction into cli/parser.py or commands/*/parser.py."),
    CheckDef("repo.no_duplicate_command_names", "repo", "ensure command names are unique", 300, check_no_duplicate_command_names, fix_hint="Rename duplicate command/alias entries."),
    CheckDef("repo.no_legacy_command_names", "repo", "forbid command names containing legacy", 300, check_no_legacy_command_names, fix_hint="Remove legacy command names and keep internal legacy reporting under `atlasctl internal legacy inventory`."),
    CheckDef("repo.no_deprecated_commands", "repo", "forbid deprecated command surfaces before 0.1 release", 300, check_no_deprecated_commands, fix_hint="Remove compat/migration/legacy top-level commands before release."),
    CheckDef("repo.registry_single_source", "repo", "enforce registry-only command/check registration points", 300, check_registry_single_source, fix_hint="Declare commands only in cli/surface_registry.py and checks only in checks/*/__init__.py."),
    CheckDef("repo.command_alias_budget", "repo", "enforce command alias/name budget", 300, check_command_alias_budget, fix_hint="Remove duplicate alias identifiers from command surface."),
    CheckDef("repo.internal_commands_not_public", "repo", "ensure unstable/internal commands are not exposed in public docs", 300, check_internal_commands_not_public, fix_hint="Mark internal commands stable=false and exclude them from public docs."),
    CheckDef("repo.public_commands_docs_index", "repo", "ensure public commands are listed in docs/commands/index.md", 300, check_public_commands_docs_index, fix_hint="Add missing public commands to packages/atlasctl/docs/commands/index.md."),
    CheckDef("repo.no_undocumented_help_commands", "repo", "forbid undocumented commands in public help surface", 300, check_no_undocumented_help_commands, fix_hint="Document command in packages/atlasctl/docs/commands/index.md or mark it internal."),
    CheckDef("repo.command_surface_stability", "repo", "enforce strict command surface compatibility against commands golden", 300, check_command_surface_stability, fix_hint="Regenerate commands goldens intentionally via `python -m atlasctl.cli gen goldens`."),
    CheckDef("repo.stable_command_no_breaking_changes", "repo", "forbid breaking changes in stable command contracts", 300, check_stable_command_no_breaking_changes, fix_hint="Avoid breaking stable command metadata or intentionally refresh commands goldens."),
    CheckDef("repo.cli_canonical_paths", "repo", "enforce canonical cli parser/dispatch/output path", 300, check_cli_canonical_paths, fix_hint="Keep parser in cli/main.py, dispatch in cli/dispatch.py, and payload formatting in cli/output.py."),
    CheckDef("repo.no_duplicate_command_impl_patterns", "repo", "forbid duplicate command implementation patterns", 300, check_no_duplicate_command_implementation_patterns, fix_hint="Pick one command implementation pattern and remove duplicate modules."),
    CheckDef("repo.command_ownership_docs", "repo", "ensure command owners are documented", 300, check_command_ownership_docs, fix_hint="Document all command owners in packages/atlasctl/docs/ownership.md."),
    CheckDef("repo.command_group_owners", "repo", "ensure every command group maps to a valid owner id", 300, check_command_group_owners, fix_hint="Update configs/meta/owners.json command_groups mapping and align with command registry owners."),
    CheckDef("repo.command_help_docs_drift", "repo", "check command help/docs drift", 500, check_command_help_docs_drift, fix_hint="Regenerate docs/_generated/cli.md from current CLI surface."),
    CheckDef("repo.public_api_exports", "repo", "enforce docs/PUBLIC_API.md coverage for __all__ exports", 300, check_public_api_exports, fix_hint="Document exported symbols in docs/PUBLIC_API.md or remove them from __all__."),
    CheckDef("repo.public_api_doc_exists", "repo", "require canonical PUBLIC_API.md documentation file", 250, check_public_api_doc_exists, fix_hint="Add packages/atlasctl/docs/PUBLIC_API.md and keep API docs there."),
    CheckDef("repo.single_registry_module", "repo", "enforce a single canonical registry.py module", 250, check_single_registry_module, fix_hint="Keep only packages/atlasctl/src/atlasctl/checks/registry.py as registry.py."),
    CheckDef("repo.single_runner_module", "repo", "enforce a single canonical runner.py module", 250, check_single_runner_module, fix_hint="Keep only packages/atlasctl/src/atlasctl/checks/runner.py as runner.py."),
    CheckDef("repo.command_module_cli_intent", "repo", "enforce command.py modules as CLI entry shims only", 250, check_command_module_cli_intent, fix_hint="Ensure command.py files include configure_* parser and run_* command entrypoints."),
    CheckDef("repo.no_wildcard_exports", "repo", "forbid wildcard imports/exports outside public surface", 250, check_no_wildcard_exports, fix_hint="Replace wildcard imports with explicit module references and __all__."),
    CheckDef("repo.contracts_namespace_purpose", "repo", "enforce contracts namespace for schema and validation modules only", 250, check_contracts_namespace_purpose, fix_hint="Keep random non-schema logic out of atlasctl/contracts and move it to proper domains."),
    CheckDef("repo.layout_domain_alias_cleanup", "repo", "forbid deprecated layout registry aliases", 250, check_layout_domain_alias_cleanup, fix_hint="Use domain-specific check packages and remove deprecated checks/layout alias modules."),
    CheckDef("repo.type_coverage", "repo", "enforce minimum type coverage in core/contracts", 600, check_type_coverage, fix_hint="Add function annotations in core/contracts until the threshold is met."),
    CheckDef("repo.dependency_declarations", "repo", "ensure pyproject dependency declarations match imports", 600, check_dependency_declarations, fix_hint="Add missing dependencies or remove unused declarations."),
    CheckDef("repo.optional_dependency_usage_gates", "repo", "forbid optional dependency usage without explicit allowlist gate", 400, check_optional_dependency_usage_gates, fix_hint="Move dependency to base deps or add justified exception in configs/policy/dependency-exceptions.json."),
    CheckDef("repo.internal_utils_stdlib_only", "repo", "prefer stdlib-only internal utility modules", 300, check_internal_utils_stdlib_only, fix_hint="Replace third-party imports in atlasctl/internal with stdlib equivalents or add a justified exception."),
    CheckDef("repo.check_module_reachability", "repo", "ensure repo check modules are imported and reachable via registry", 300, check_repo_check_modules_registered, fix_hint="Import new repo check modules in checks/tools/repo_domain/__init__.py."),
    CheckDef("repo.dead_modules", "repo", "ensure dead modules analyzer runs and returns canonical payload", 300, check_dead_modules_report_runs, fix_hint="Keep policies/dead_modules.py runnable and deterministic."),
    CheckDef("repo.dead_module_reachability", "repo", "enforce dead module candidates are explicitly allowlisted", 300, check_dead_module_reachability_allowlist, fix_hint="Update configs/policy/dead-modules-allowlist.json with intended exceptions."),
    CheckDef("repo.legacy_zero_importers", "repo", "require zero importers of removed atlasctl legacy namespace", 300, check_no_legacy_importers, fix_hint="Remove imports/references to " + "atlasctl." + "legacy" + "."),
    CheckDef("repo.pyproject_required_blocks", "repo", "ensure pyproject contains required project and tool config blocks", 300, check_pyproject_required_blocks, fix_hint="Add required [project]/[tool.*] blocks to packages/atlasctl/pyproject.toml."),
    CheckDef("repo.version_matches_pyproject", "repo", "ensure atlasctl package version and --version output match pyproject", 300, check_version_matches_pyproject, fix_hint="Align atlasctl.__version__ with pyproject [project].version and keep --version output stable outside git repos.", effects=("subprocess",)),
    CheckDef("repo.packaging_metadata_completeness", "repo", "ensure pyproject packaging metadata is complete (classifiers and project URLs)", 300, check_packaging_metadata_completeness, fix_hint="Add required project classifiers and URLs in packages/atlasctl/pyproject.toml."),
    CheckDef("repo.pyproject_no_duplicate_tool_config", "repo", "forbid duplicate tool config files beside pyproject", 300, check_pyproject_no_duplicate_tool_config, fix_hint="Remove duplicated tool config files and keep pyproject as SSOT."),
    CheckDef("repo.console_script_entry", "repo", "ensure atlasctl console script entry exists and points to callable target", 300, check_console_script_entry, fix_hint="Set [project.scripts] atlasctl = \"atlasctl.cli.main:main\" and ensure target is importable."),
    CheckDef("repo.python_module_help", "repo", "ensure python -m atlasctl --help works", 300, check_python_module_help, fix_hint="Ensure atlasctl package entrypoint remains runnable with python -m atlasctl.", effects=("subprocess",)),
    CheckDef("repo.optional_dependency_groups", "repo", "ensure required pyproject optional-dependency groups exist and are non-empty", 300, check_optional_dependency_groups, fix_hint="Add required [project.optional-dependencies] groups with entries: dev/ci/test/ops/docs."),
    CheckDef("repo.python_requires_version_and_ci", "repo", "enforce pyproject requires-python and CI python version alignment", 300, check_python_requires_version_and_ci, fix_hint="Pin requires-python to >=3.11 and set actions/setup-python python-version: 3.11 in CI."),
    CheckDef("repo.pyproject_minimalism", "repo", "forbid dead/unknown pyproject tool keys", 300, check_pyproject_minimalism, fix_hint="Remove unknown [tool.*] sections or document and allow them explicitly."),
    CheckDef("repo.deps_workflow_doc", "repo", "ensure docs/deps.md matches chosen dependency workflow", 300, check_deps_workflow_doc, fix_hint="Update docs/deps.md and keep requirements.in/requirements.lock.txt in sync."),
    CheckDef("repo.env_docs_present", "repo", "ensure docs/env.md exists and lists canonical env vars", 300, check_env_docs_present, fix_hint="Create docs/env.md and document canonical runtime environment variables."),
    CheckDef("repo.requirements_artifact_policy", "repo", "ensure only route-B requirements artifacts exist", 300, check_requirements_artifact_policy, fix_hint="Keep only requirements.in and requirements.lock.txt in package root for route-B workflow."),
    CheckDef("repo.requirements_sync", "repo", "ensure requirements files match pyproject dev dependency declarations", 300, check_requirements_sync_with_pyproject, fix_hint="Regenerate requirements.lock.txt from requirements.in and keep pyproject optional-deps dev aligned."),
    CheckDef("repo.dependency_owner_justification", "repo", "ensure each dependency has owner and justification", 300, check_dependency_owner_justification, fix_hint="Add dependency ownership + justification entries in docs/deps.md."),
    CheckDef("repo.dependency_gate_targets", "repo", "ensure dependency gate make targets exist", 300, check_dependency_gate_targets, fix_hint="Define atlasctl/internal/deps/lock/atlasctl/internal/deps/sync/atlasctl/internal/deps/check-venv/atlasctl/internal/deps/cold-start in makefiles/atlasctl.mk."),
    CheckDef("repo.workflows_targets_exist", "repo", "ensure make targets used by workflows exist", 300, check_workflows_targets_exist, fix_hint="Add missing make targets or update workflows to existing targets.", effects=("subprocess",)),
    CheckDef("repo.ci_workflow_policy", "repo", "enforce workflow command policy (make/atlasctl wrappers only)", 300, check_ci_workflow_policy, fix_hint="Use make thin wrappers or ./bin/atlasctl in workflows; avoid python -m atlasctl and raw cargo commands."),
    CheckDef("repo.ci_artifact_upload_policy", "repo", "enforce workflow artifact upload roots and always-on policy", 300, check_ci_artifact_upload_policy, fix_hint="Upload artifacts only from approved roots and always use if: always()."),
    CheckDef("repo.deps_command_surface", "repo", "ensure atlasctl deps command surface is runnable", 300, check_deps_command_surface, fix_hint="Wire atlasctl deps parser/runner and keep command import path valid."),
    CheckDef("repo.tests_no_duplicate_expectations", "repo", "forbid duplicate test function names across test modules", 300, check_test_duplicate_expectations, fix_hint="Rename duplicated test_* functions to avoid conflicting expectations."),
    CheckDef("repo.test_taxonomy_layout", "repo", "enforce test taxonomy and placement invariants", 300, check_test_taxonomy_layout, fix_hint="Place tests under domain folders and align declared # test-taxonomy with placement."),
    CheckDef("repo.test_no_unmarked_network", "repo", "forbid test network usage unless marked", 300, check_no_unmarked_test_network, fix_hint="Add @pytest.mark.network or '# network-test: allowed' near intentional network tests."),
    CheckDef("repo.test_write_sandbox", "repo", "forbid writes outside temp/artifacts isolation sandbox in tests", 300, check_test_write_sandbox, fix_hint="Write via tmp_path/tempfile or artifacts/isolate run directories only."),
    CheckDef("repo.test_determinism_patterns", "repo", "forbid nondeterministic test patterns without explicit marker", 300, check_test_determinism_patterns, fix_hint="Replace unstable time/random/env usage or annotate with determinism-allow: reason."),
    CheckDef("repo.test_no_duplicated_coverage", "repo", "forbid duplicated golden coverage across multiple tests", 300, check_no_duplicated_coverage_paths, fix_hint="Keep one canonical test per golden surface and remove duplicate assertions."),
    CheckDef("repo.output_format_stability", "repo", "enforce output formatting stability across OS", 300, check_output_format_stability, fix_hint="Use LF-only snapshots and avoid platform-dependent line separator logic."),
    CheckDef("repo.test_skip_justification", "repo", "forbid skipped tests without justification and expiry markers", 300, check_no_unjustified_skips, fix_hint="Add skip-justification and skip-expires markers near skip usage."),
    CheckDef("repo.json_golden_conflicts", "repo", "forbid conflicting JSON goldens for the same schema surface", 300, check_no_conflicting_json_goldens, fix_hint="Keep one .json.golden per schema surface."),
    CheckDef("repo.duplicate_contract_assertions", "repo", "forbid duplicate contract assertions inside one test module", 300, check_duplicate_contract_assertions, fix_hint="Consolidate duplicate validate(schema) assertions into one test."),
    CheckDef("repo.test_ownership_tags", "repo", "ensure tests declare ownership tags or live in domain directories", 300, check_test_ownership_tags, fix_hint="Add '# test-domain: <domain>' header to top-level tests."),
    CheckDef("repo.suite_marker_rules", "repo", "enforce check-suite-coverage marker file policy", 300, check_suite_marker_rules, fix_hint="Keep tests/goldens/check/check-suite-coverage.markers.txt sorted, unique, and only registered check ids."),
    CheckDef("repo.command_test_coverage", "repo", "ensure each command has explicit test coverage marker", 300, check_command_test_coverage, fix_hint="Add at least one test mentioning each command."),
    CheckDef("repo.json_goldens_validate_schema", "repo", "require schema validation in JSON golden tests", 300, check_json_goldens_validate_schema, fix_hint="Call contracts.validate() before asserting JSON golden snapshots."),
    CheckDef("repo.check_test_coverage", "repo", "ensure each registered check has test or golden coverage marker", 300, check_check_test_coverage, fix_hint="Add test/golden references for uncovered checks."),
    CheckDef(
        "repo.suite_inventory_policy",
        "repo",
        "validate suite inventory coverage and required tag policy",
        300,
        check_suite_inventory_policy,
        fix_hint="Assign checks to suites and ensure required complete suites include all required checks.",
    ),
    CheckDef("repo.required_target_shape", "repo", "enforce package root minimalism and src no-symlink target shape", 300, check_required_target_shape, fix_hint="Keep package-root items minimal and remove symlinks from src tree."),
    CheckDef("repo.internal_import_boundaries", "repo", "forbid atlasctl.internal imports outside internal namespace", 300, check_internal_import_boundaries, fix_hint="Route shared helpers through public modules instead of atlasctl.internal."),
    CheckDef("repo.modern_no_legacy_imports", "repo", "forbid modern modules from importing " + "atlasctl." + "legacy", 300, check_no_modern_imports_from_legacy, fix_hint="Migrate callers to canonical modules under atlasctl.core/commands/checks."),
    CheckDef("repo.no_legacy_module_paths", "repo", "forbid legacy module paths in atlasctl src tree", 300, check_no_legacy_module_paths, fix_hint="Delete or move modules out of any */legacy/* path."),
    CheckDef("repo.modern_no_legacy_obs_imports", "repo", "forbid modern modules from importing " + "atlasctl." + "legacy" + ".obs", 300, check_no_legacy_obs_imports_in_modern, fix_hint="Migrate observability imports to atlasctl.observability."),
    CheckDef("repo.no_deprecated_namespaces", "repo", "forbid imports from atlasctl.check/report/obs namespaces", 300, check_forbidden_deprecated_namespaces, fix_hint="Use atlasctl.checks and atlasctl.reporting canonical namespaces."),
    CheckDef("repo.no_deprecated_namespace_dirs", "repo", "forbid deprecated atlasctl/check report obs directories", 300, check_forbidden_deprecated_namespace_dirs, fix_hint="Remove deprecated namespace directories and keep checks/reporting/observability as canonical roots."),
    CheckDef("repo.no_core_integration_dir", "repo", "forbid deprecated core/integration namespace", 300, check_forbidden_core_integration_dir, fix_hint="Use top-level atlasctl.adapters for integration concerns."),
    CheckDef("repo.contract_import_boundaries", "repo", "enforce contracts/core-contracts import boundaries", 300, check_contract_import_boundaries, fix_hint="Commands/checks should import schema contracts from atlasctl.contracts only."),
    CheckDef("repo.runcontext_single_builder", "repo", "ensure RunContext is built only in core/context.py", 300, check_runcontext_single_builder, fix_hint="Use RunContext.from_args and avoid constructing context-like objects elsewhere."),
    CheckDef("repo.command_import_lint", "repo", "enforce command module import boundaries", 300, check_command_import_lint, fix_hint="Restrict command imports to core/contracts/checks/adapters/commands/cli."),
    CheckDef("repo.checks_import_lint", "repo", "enforce checks module import boundaries", 300, check_checks_import_lint, fix_hint="Restrict checks imports to core/contracts/reporting/adapters/checks."),
    CheckDef("repo.commands_no_check_impl_imports", "repo", "forbid commands from importing check implementations directly", 300, check_commands_no_check_impl_imports, fix_hint="Resolve checks through registry and engine selectors rather than direct check module imports."),
    CheckDef("repo.commands_check_no_domain_imports", "repo", "forbid commands/check modules from importing domain checks directly", 300, check_commands_check_no_domain_imports, fix_hint="Resolve checks through checks.registry and selectors, not checks.domains modules."),
    CheckDef("repo.core_no_command_imports", "repo", "forbid core modules from importing command/cli layers", 300, check_core_no_command_imports, fix_hint="Keep core independent from command and cli glue layers."),
    CheckDef("repo.checks_no_command_imports", "repo", "forbid checks from importing command modules", 300, check_checks_no_command_imports, fix_hint="Move reusable logic from commands into runtime/registry modules consumed by both."),
    CheckDef("repo.checks_no_commands_check_imports", "repo", "forbid checks modules from importing commands/check modules", 300, check_checks_no_commands_check_imports, fix_hint="Keep checks independent from command adapters; use shared runtime or registry modules."),
    CheckDef("repo.checks_no_cli_imports", "repo", "forbid checks modules from importing cli layer", 300, check_checks_no_cli_imports, fix_hint="Keep checks pure and independent from cli modules."),
    CheckDef("repo.cli_import_scope", "repo", "restrict cli imports to commands/core and approved runtime shims", 300, check_cli_import_scope, fix_hint="Route feature logic through commands; keep cli as parser/dispatch glue."),
    CheckDef("repo.cli_render_boundary", "repo", "require cli error rendering to live in cli/render.py only", 300, check_cli_render_boundary, fix_hint="Define render_error only in atlasctl/cli/render.py and import it from callers."),
    CheckDef("repo.registry_definition_boundary", "repo", "forbid registry modules from importing command/cli/suite/check runtime modules", 300, check_registry_definition_boundary, fix_hint="Keep registry declarative and independent from runtime command/check implementations."),
    CheckDef("repo.checks_canonical_location", "repo", "require check implementations under atlasctl/checks canonical tree", 300, check_checks_canonical_location, fix_hint="Move check_*.py implementations under packages/atlasctl/src/atlasctl/checks/ or extend migration allowlist explicitly."),
    CheckDef("repo.check_impl_no_cli_imports", "repo", "forbid direct CLI imports from check implementation files", 300, check_check_impl_no_cli_imports, fix_hint="Keep check implementations pure and route CLI wiring through commands/cli modules."),
    CheckDef("repo.main_entrypoint_calls_app_main", "repo", "require __main__ to delegate to atlasctl.app.main", 300, check_main_entrypoint_calls_app_main, fix_hint="Keep __main__.py as a thin one-line app.main handoff."),
    CheckDef("repo.cli_main_loc_budget", "repo", "enforce LOC budget for cli/main.py", 300, check_cli_main_loc_budget, fix_hint="Move business logic into commands/runtime/engine modules and keep cli/main.py thin."),
    CheckDef("repo.registry_generated_readonly", "repo", "require REGISTRY.generated.json to be generator-owned", 300, check_registry_generated_readonly, fix_hint="Run ./bin/atlasctl dev regen-registry and commit the regenerated artifacts."),
    CheckDef("repo.effect_boundaries", "repo", "forbid direct subprocess/fs/env/network effects outside core boundaries", 300, check_forbidden_effect_calls, fix_hint="Route effects through core.exec/core.process/core.fs/core.runtime.env/core.network."),
    CheckDef("repo.managed_artifact_write_roots", "repo", "enforce managed write roots under artifacts and reject out-of-root writes", 300, check_managed_artifact_write_roots, fix_hint="Keep managed write roots under artifacts/ and route writes through core.fs."),
    CheckDef("repo.config_generated_no_human_refs", "repo", "forbid human-facing docs/workflows/makefiles from referencing configs/_generated directly", 300, check_config_generated_no_human_refs, fix_hint="Reference `atlasctl configs ...` commands instead of configs/_generated paths."),
    CheckDef("repo.makefiles_no_deep_config_paths", "repo", "forbid deep hardcoded config paths in makefiles", 300, check_makefiles_no_deep_config_paths, fix_hint="Route config resolution through atlasctl configs compiler commands."),
    CheckDef("repo.config_generated_headers_and_checksums", "repo", "detect hand-edits/stale files under configs/_generated via headers and checksums", 300, check_config_generated_headers_and_checksums, fix_hint="Re-run `atlasctl configs gen` and avoid manual edits under configs/_generated."),
    CheckDef("repo.ops_inventory_schema_coverage", "repo", "require schema coverage/contracts-map entries for ops inventory files", 300, check_ops_inventory_schema_coverage, fix_hint="Add ops/inventory/contracts-map.json entries and schemas for new inventory files."),
    CheckDef("repo.config_lock_discipline", "repo", "verify config compiler lock artifacts for toolchain/helm/pinned queries", 300, check_config_lock_discipline, fix_hint="Keep toolchain/helm/pinned query lock artifacts present and valid."),
    CheckDef("repo.config_migration_cutoff_legacy_locations", "repo", "forbid legacy config inventory locations after migration cutoff", 300, check_config_migration_cutoff_legacy_locations, fix_hint="Delete legacy configs/inventory paths after new config pipeline is green."),
    CheckDef("repo.ops_workflow_evidence_path_policy", "repo", "enforce first-class ops workflow outputs under artifacts/runs/<run_id>/ops", 300, check_ops_workflow_evidence_path_policy, fix_hint="Use atlasctl.ops.workflows.paths ops_run_root/ops_run_area_dir helpers."),
    CheckDef("repo.ops_helm_render_inventory_drift", "repo", "enforce ops helm/chart metadata alignment with inventory + values schema presence", 300, check_ops_helm_render_inventory_drift, fix_hint="Align ops/inventory/layers.json release metadata with Chart.yaml and keep values.schema.json valid."),
    CheckDef("repo.ops_images_pinned_to_digests_policy", "repo", "enforce policy-driven image digest pinning for ops toolchain inventory", 300, check_ops_images_pinned_to_digests_policy, fix_hint="Pin toolchain image refs to digests or update configs/policy/ops-image-digest-policy.json intentionally."),
    CheckDef("repo.ops_helm_versions_pinned", "repo", "forbid floating helm chart versions and require helm pin manifest shape", 300, check_ops_helm_versions_pinned, fix_hint="Use explicit chart/app versions and keep configs/ops/pins/helm.json helm mapping present."),
    CheckDef("repo.ops_namespaces_inventory_manifest_agreement", "repo", "ensure namespace SSOT/inventory/chart values agree", 300, check_ops_namespaces_inventory_manifest_agreement, fix_hint="Align configs/ops/namespaces.json, ops/inventory/layers.json, and chart values namespace."),
    CheckDef("repo.ops_ports_and_surfaces_contract", "repo", "ensure ports and surface inventory align with configs and docs", 300, check_ops_ports_and_surfaces_contract, fix_hint="Align ops/inventory/layers.json ports with configs/ops/ports.json and keep docs/operations/e2e/stack.md updated."),
    CheckDef("repo.ops_observability_assets_public_surfaces", "repo", "ensure observability assets reference every public ops service surface", 300, check_ops_observability_assets_for_public_surfaces, fix_hint="Add observability assets/contracts/dashboards/alerts for missing services."),
    CheckDef("repo.ops_load_thresholds_exist_for_every_suite", "repo", "require per-suite load threshold files under ops/load/thresholds", 300, check_ops_load_thresholds_exist_for_every_suite, fix_hint="Add ops/load/thresholds/<suite>.thresholds.json for each suite in ops/load/suites/suites.json."),
    CheckDef("repo.subprocess_boundary", "repo", "restrict subprocess imports to core execution boundary", 300, check_subprocess_boundary, fix_hint="Use core.exec/core.process for subprocess calls."),
    CheckDef("repo.effect_boundary_exceptions_policy", "repo", "enforce explicit sorted effect boundary exceptions with reasons", 300, check_effect_boundary_exceptions_policy, fix_hint="Keep configs/policy/effect-boundary-exceptions.json sorted and justified."),
    CheckDef("repo.compileall_gate", "repo", "ensure atlasctl source compiles with compileall", 300, check_compileall_gate, fix_hint="Fix syntax/import issues until python -m compileall passes."),
    CheckDef("repo.import_smoke", "repo", "ensure atlasctl package imports in minimal environment", 300, check_import_smoke, fix_hint="Keep top-level imports light and dependency-safe."),
    CheckDef("repo.cold_import_budget", "repo", "enforce cold import time budget for atlasctl package", 300, check_cold_import_budget, fix_hint="Reduce top-level imports and defer heavy initialization."),
)
