pub const MIN_POLICY_SCHEMA_VERSION: u32 = 1;
pub const MAX_SCHEMA_BUMP_STEP: u32 = 1;

pub const DEFAULT_MAX_SERIALIZATION_BYTES: u64 = 512 * 1024;
pub const DEFAULT_HEAVY_PROJECTION_LIMIT: u32 = 200;
