from __future__ import annotations

from .enforcement import (
    check_ci_pr_lane_fast_only,
    check_make_ci_entrypoints_contract,
    check_make_index_drift_contract,
    check_make_no_orphan_docs_refs,
    check_make_no_direct_artifact_writes,
    check_make_no_bypass_atlasctl_without_allowlist,
    check_make_no_direct_script_exec_drift,
    check_make_no_direct_python_only_atlasctl,
    check_make_no_direct_bash_ops,
    check_make_no_legacy_script_aliases,
    check_make_no_direct_scripts_only_atlasctl,
    check_make_lane_reports_via_atlasctl_reporting,
    check_ci_workflows_call_make_and_make_calls_atlasctl,
    check_public_make_targets_map_to_atlasctl,
    check_make_public_targets_documented,
    check_make_wrapper_purity,
    check_make_no_python_module_invocation,
    check_make_root_budget,
    check_make_target_boundaries_enforced,
    check_make_target_ownership_complete,
    check_workflows_reference_known_suites,
)
from ....repo.native import (
    check_make_command_allowlist,
    check_make_forbidden_paths,
    check_make_help,
    check_make_no_direct_python_script_invocations,
    check_make_scripts_references,
)
from ....core.base import CheckDef

CHECKS: tuple[CheckDef, ...] = (
    CheckDef(
        "make.no_direct_scripts_only_atlasctl",
        "make",
        "forbid direct script path invocations in make recipes",
        1000,
        check_make_no_direct_scripts_only_atlasctl,
        fix_hint="Delegate script execution through atlasctl commands.",
    ),
    CheckDef(
        "make.no_direct_python_only_atlasctl",
        "make",
        "forbid direct python invocations in make recipes",
        1000,
        check_make_no_direct_python_only_atlasctl,
        fix_hint="Use atlasctl entrypoints instead of direct python invocations.",
    ),
    CheckDef(
        "make.no_direct_bash_ops",
        "make",
        "forbid direct `bash ops/...` invocations in make recipes",
        1000,
        check_make_no_direct_bash_ops,
        fix_hint="Route ops scripts through atlasctl make/ops commands.",
    ),
    CheckDef(
        "make.no_direct_artifact_writes",
        "make",
        "forbid direct artifact writes in make recipes",
        1000,
        check_make_no_direct_artifact_writes,
        fix_hint="Write artifacts via atlasctl reporting and command surfaces only.",
    ),
    CheckDef(
        "make.lane_reports_via_atlasctl_reporting",
        "make",
        "require lane reports to be emitted through atlasctl reporting command",
        900,
        check_make_lane_reports_via_atlasctl_reporting,
        fix_hint="Use `atlasctl report make-area-write` for lane report emission.",
    ),
    CheckDef(
        "make.ci_entrypoints_contract",
        "make",
        "validate CI workflow entrypoints contract",
        900,
        check_make_ci_entrypoints_contract,
        fix_hint="Keep workflow run commands on approved make/atlasctl entrypoints.",
    ),
    CheckDef(
        "make.ci_workflows_make_only",
        "make",
        "require CI workflows to call make entrypoints and keep atlasctl delegation in makefiles",
        900,
        check_ci_workflows_call_make_and_make_calls_atlasctl,
        fix_hint="Use `run: make <target>` in workflows and keep atlasctl delegation in makefiles.",
    ),
    CheckDef(
        "make.ci_pr_lane_fast_only",
        "make",
        "require CI PR lane suites to exclude slow checks unless explicitly allowlisted",
        900,
        check_ci_pr_lane_fast_only,
        fix_hint="Keep `local` suite fast-only, or add temporary exceptions in configs/policy/ci-pr-slow-allowlist.json.",
    ),
    CheckDef(
        "make.workflows_reference_known_suites",
        "make",
        "require workflow suite invocations to reference declared suite names",
        900,
        check_workflows_reference_known_suites,
        fix_hint="Update workflow suite names or registry/suites catalog entries so they match.",
    ),
    CheckDef(
        "make.public_targets_documented",
        "make",
        "require documented public make targets",
        900,
        check_make_public_targets_documented,
        fix_hint="Document every public make target in generated/public docs.",
    ),
    CheckDef(
        "make.target_ownership_complete",
        "make",
        "require make target ownership coverage",
        900,
        check_make_target_ownership_complete,
        fix_hint="Add missing make target ownership metadata.",
    ),
    CheckDef(
        "make.public_target_atlasctl_mapping",
        "make",
        "require every public make target to delegate to atlasctl",
        900,
        check_public_make_targets_map_to_atlasctl,
        fix_hint="Update public make target recipe bodies to call atlasctl wrappers only.",
    ),
    CheckDef(
        "make.wrapper_purity",
        "make",
        "enforce make wrapper purity for canonical makefiles",
        1000,
        check_make_wrapper_purity,
        fix_hint="Use single-line ./bin/atlasctl delegation in canonical makefiles.",
    ),
    CheckDef(
        "make.no_python_module_invocation",
        "make",
        "forbid `python -m atlasctl.cli` in make recipes",
        1000,
        check_make_no_python_module_invocation,
        fix_hint="Use ./bin/atlasctl in make recipes.",
    ),
    CheckDef(
        "make.no_legacy_script_aliases",
        "make",
        "forbid legacy make alias tokens (ATLAS_SCRIPTS/SCRIPTS/PY_RUN)",
        1000,
        check_make_no_legacy_script_aliases,
        fix_hint="Use ./bin/atlasctl or $(ATLASCTL) wrappers only.",
    ),
    CheckDef(
        "make.root_budget",
        "make",
        "enforce root.mk LOC/target-count budget",
        1000,
        check_make_root_budget,
        fix_hint="Reduce root.mk orchestration surface and keep only public wrappers.",
    ),
    CheckDef(
        "make.target_boundaries_enforced",
        "make",
        "enforce make target boundary contracts",
        900,
        check_make_target_boundaries_enforced,
        fix_hint="Keep target cross-area dependencies within contract boundaries.",
    ),
    CheckDef(
        "make.index_drift_contract",
        "make",
        "enforce makefiles index drift contract",
        900,
        check_make_index_drift_contract,
        fix_hint="Regenerate and commit makefiles index changes.",
    ),
    CheckDef(
        "make.no_orphan_docs_refs",
        "make",
        "forbid orphan docs references for make targets and atlasctl commands",
        900,
        check_make_no_orphan_docs_refs,
        fix_hint="Update docs index and command references so docs links are reachable.",
    ),
    CheckDef("make.scripts_refs", "make", "forbid scripts/ references in make recipes", 1000, check_make_scripts_references, fix_hint="Replace scripts/ invocations with atlasctl commands."),
    CheckDef("make.help_determinism", "make", "ensure deterministic make help output", 2000, check_make_help, fix_hint="Regenerate and normalize make help output."),
    CheckDef("make.forbidden_paths", "make", "forbid direct forbidden paths in make recipes", 1000, check_make_forbidden_paths, fix_hint="Route commands through allowed wrappers."),
    CheckDef("make.command_allowlist", "make", "enforce allowed direct recipe commands", 1500, check_make_command_allowlist, fix_hint="Use allowed command wrappers in make targets."),
    CheckDef("make.no_direct_python", "make", "forbid direct python script execution in make recipes", 1000, check_make_no_direct_python_script_invocations, fix_hint="Replace `python3 path/to/script.py` with atlasctl commands."),
    CheckDef("make.no_direct_script_exec_drift", "make", "drift check for direct script execution in make recipes", 1000, check_make_no_direct_script_exec_drift, fix_hint="Replace direct script execution with atlasctl command wrappers."),
    CheckDef("make.no_bypass_atlasctl", "make", "forbid make recipes bypassing atlasctl without explicit allowlist", 1000, check_make_no_bypass_atlasctl_without_allowlist, fix_hint="Route recipe logic through atlasctl, or add a documented delegation exception."),
)
