name: publish-bijux-atlas-client

on:
  workflow_dispatch:
  push:
    tags:
      - "bijux-atlas-client-v*"

jobs:
  validate-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7
      - name: Validate Rust client crate
        run: |
          cargo test --locked -p bijux-atlas-client -- --nocapture
          cargo check --locked -p bijux-atlas-client --examples
          cargo bench --locked -p bijux-atlas-client --no-run
      - name: Package crate
        run: cargo package --locked -p bijux-atlas-client --allow-dirty
