name: publish-bijux-atlas-client

on:
  workflow_dispatch:
  push:
    tags:
      - "bijux-atlas-client-v*"

jobs:
  validate-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7
      - name: Validate Rust client crate
        run: |
          cargo test -p bijux-atlas-client -- --nocapture
          cargo check -p bijux-atlas-client --examples
          cargo bench -p bijux-atlas-client --no-run
      - name: Package crate
        run: cargo package -p bijux-atlas-client --allow-dirty
